"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _MsgType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _MsgTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_MsgType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    MSG_TYPE_UNKNOWN: _MsgType.ValueType  # 0
    MSG_TYPE_PING: _MsgType.ValueType  # 1
    MSG_TYPE_PONG: _MsgType.ValueType  # 2
    MSG_TYPE_SET_SETTINGS_REQUEST: _MsgType.ValueType  # 3
    """Settings"""
    MSG_TYPE_SET_SETTINGS_RESPONSE: _MsgType.ValueType  # 4
    MSG_TYPE_SET_LIST_START_REQUEST: _MsgType.ValueType  # 5
    """List upload (chunked)"""
    MSG_TYPE_SET_LIST_START_RESPONSE: _MsgType.ValueType  # 6
    MSG_TYPE_LIST_CHUNK: _MsgType.ValueType  # 7
    MSG_TYPE_SET_LIST_COMPLETE_RESPONSE: _MsgType.ValueType  # 8
    MSG_TYPE_START_SCAN_REQUEST: _MsgType.ValueType  # 9
    """Scan"""
    MSG_TYPE_START_SCAN_RESPONSE: _MsgType.ValueType  # 10
    MSG_TYPE_GET_RESULTS_REQUEST: _MsgType.ValueType  # 11
    """Results (chunked)"""
    MSG_TYPE_RESULTS_CHUNK: _MsgType.ValueType  # 12
    MSG_TYPE_GET_STATUS_REQUEST: _MsgType.ValueType  # 13
    """Status"""
    MSG_TYPE_GET_STATUS_RESPONSE: _MsgType.ValueType  # 14
    MSG_TYPE_REBOOT_REQUEST: _MsgType.ValueType  # 19
    """Reboot"""
    MSG_TYPE_GET_TRANSFORMED_LIST_REQUEST: _MsgType.ValueType  # 20
    """Transformed list (diagnostic)"""
    MSG_TYPE_TRANSFORMED_LIST_CHUNK: _MsgType.ValueType  # 21
    MSG_TYPE_GET_DEVICE_INFO_REQUEST: _MsgType.ValueType  # 22
    """Device info"""
    MSG_TYPE_GET_DEVICE_INFO_RESPONSE: _MsgType.ValueType  # 23
    MSG_TYPE_RAW_CAPTURE_REQUEST: _MsgType.ValueType  # 24
    """Raw capture (noise characterization)"""
    MSG_TYPE_RAW_CAPTURE_CHUNK: _MsgType.ValueType  # 25
    MSG_TYPE_RESULT_POINT: _MsgType.ValueType  # 26
    """Per-point result streaming"""
    MSG_TYPE_RESULT_POINT_NAK: _MsgType.ValueType  # 27
    """Reliable streaming (NAK-based retransmission)"""
    MSG_TYPE_RESULT_POINT_RETRANSMIT: _MsgType.ValueType  # 28
    MSG_TYPE_FW_UPDATE_START_REQUEST: _MsgType.ValueType  # 29
    """Firmware update"""
    MSG_TYPE_FW_UPDATE_START_RESPONSE: _MsgType.ValueType  # 30
    MSG_TYPE_FW_UPDATE_CHUNK: _MsgType.ValueType  # 31
    MSG_TYPE_FW_UPDATE_CHUNK_ACK: _MsgType.ValueType  # 32
    MSG_TYPE_FW_UPDATE_FINISH_REQUEST: _MsgType.ValueType  # 33
    MSG_TYPE_FW_UPDATE_FINISH_RESPONSE: _MsgType.ValueType  # 34
    MSG_TYPE_FW_UPDATE_STATUS_REQUEST: _MsgType.ValueType  # 35
    MSG_TYPE_FW_UPDATE_STATUS_RESPONSE: _MsgType.ValueType  # 36
    MSG_TYPE_FW_BOOT_CONFIRM_REQUEST: _MsgType.ValueType  # 37
    MSG_TYPE_FW_BOOT_CONFIRM_RESPONSE: _MsgType.ValueType  # 38
    MSG_TYPE_RESULTS_CHUNK_NAK: _MsgType.ValueType  # 39
    """Reliable bulk transfer (NAK-based retransmission for results chunks)"""
    MSG_TYPE_RESULTS_CHUNK_RETRANSMIT: _MsgType.ValueType  # 40

class MsgType(_MsgType, metaclass=_MsgTypeEnumTypeWrapper): ...

MSG_TYPE_UNKNOWN: MsgType.ValueType  # 0
MSG_TYPE_PING: MsgType.ValueType  # 1
MSG_TYPE_PONG: MsgType.ValueType  # 2
MSG_TYPE_SET_SETTINGS_REQUEST: MsgType.ValueType  # 3
"""Settings"""
MSG_TYPE_SET_SETTINGS_RESPONSE: MsgType.ValueType  # 4
MSG_TYPE_SET_LIST_START_REQUEST: MsgType.ValueType  # 5
"""List upload (chunked)"""
MSG_TYPE_SET_LIST_START_RESPONSE: MsgType.ValueType  # 6
MSG_TYPE_LIST_CHUNK: MsgType.ValueType  # 7
MSG_TYPE_SET_LIST_COMPLETE_RESPONSE: MsgType.ValueType  # 8
MSG_TYPE_START_SCAN_REQUEST: MsgType.ValueType  # 9
"""Scan"""
MSG_TYPE_START_SCAN_RESPONSE: MsgType.ValueType  # 10
MSG_TYPE_GET_RESULTS_REQUEST: MsgType.ValueType  # 11
"""Results (chunked)"""
MSG_TYPE_RESULTS_CHUNK: MsgType.ValueType  # 12
MSG_TYPE_GET_STATUS_REQUEST: MsgType.ValueType  # 13
"""Status"""
MSG_TYPE_GET_STATUS_RESPONSE: MsgType.ValueType  # 14
MSG_TYPE_REBOOT_REQUEST: MsgType.ValueType  # 19
"""Reboot"""
MSG_TYPE_GET_TRANSFORMED_LIST_REQUEST: MsgType.ValueType  # 20
"""Transformed list (diagnostic)"""
MSG_TYPE_TRANSFORMED_LIST_CHUNK: MsgType.ValueType  # 21
MSG_TYPE_GET_DEVICE_INFO_REQUEST: MsgType.ValueType  # 22
"""Device info"""
MSG_TYPE_GET_DEVICE_INFO_RESPONSE: MsgType.ValueType  # 23
MSG_TYPE_RAW_CAPTURE_REQUEST: MsgType.ValueType  # 24
"""Raw capture (noise characterization)"""
MSG_TYPE_RAW_CAPTURE_CHUNK: MsgType.ValueType  # 25
MSG_TYPE_RESULT_POINT: MsgType.ValueType  # 26
"""Per-point result streaming"""
MSG_TYPE_RESULT_POINT_NAK: MsgType.ValueType  # 27
"""Reliable streaming (NAK-based retransmission)"""
MSG_TYPE_RESULT_POINT_RETRANSMIT: MsgType.ValueType  # 28
MSG_TYPE_FW_UPDATE_START_REQUEST: MsgType.ValueType  # 29
"""Firmware update"""
MSG_TYPE_FW_UPDATE_START_RESPONSE: MsgType.ValueType  # 30
MSG_TYPE_FW_UPDATE_CHUNK: MsgType.ValueType  # 31
MSG_TYPE_FW_UPDATE_CHUNK_ACK: MsgType.ValueType  # 32
MSG_TYPE_FW_UPDATE_FINISH_REQUEST: MsgType.ValueType  # 33
MSG_TYPE_FW_UPDATE_FINISH_RESPONSE: MsgType.ValueType  # 34
MSG_TYPE_FW_UPDATE_STATUS_REQUEST: MsgType.ValueType  # 35
MSG_TYPE_FW_UPDATE_STATUS_RESPONSE: MsgType.ValueType  # 36
MSG_TYPE_FW_BOOT_CONFIRM_REQUEST: MsgType.ValueType  # 37
MSG_TYPE_FW_BOOT_CONFIRM_RESPONSE: MsgType.ValueType  # 38
MSG_TYPE_RESULTS_CHUNK_NAK: MsgType.ValueType  # 39
"""Reliable bulk transfer (NAK-based retransmission for results chunks)"""
MSG_TYPE_RESULTS_CHUNK_RETRANSMIT: MsgType.ValueType  # 40
Global___MsgType: _TypeAlias = MsgType  # noqa: Y015

class _TransferMode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _TransferModeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_TransferMode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    TRANSFER_MODE_BULK: _TransferMode.ValueType  # 0
    TRANSFER_MODE_PER_POINT: _TransferMode.ValueType  # 1

class TransferMode(_TransferMode, metaclass=_TransferModeEnumTypeWrapper):
    """--- Scan ---"""

TRANSFER_MODE_BULK: TransferMode.ValueType  # 0
TRANSFER_MODE_PER_POINT: TransferMode.ValueType  # 1
Global___TransferMode: _TypeAlias = TransferMode  # noqa: Y015

class _FwUpdateStatus:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _FwUpdateStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_FwUpdateStatus.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    FW_UPDATE_STATUS_IDLE: _FwUpdateStatus.ValueType  # 0
    FW_UPDATE_STATUS_RECEIVING: _FwUpdateStatus.ValueType  # 1
    FW_UPDATE_STATUS_VERIFYING: _FwUpdateStatus.ValueType  # 2
    FW_UPDATE_STATUS_BOOT_PENDING: _FwUpdateStatus.ValueType  # 3
    FW_UPDATE_STATUS_CONFIRMED: _FwUpdateStatus.ValueType  # 4

class FwUpdateStatus(_FwUpdateStatus, metaclass=_FwUpdateStatusEnumTypeWrapper):
    """--- Firmware Update ---"""

FW_UPDATE_STATUS_IDLE: FwUpdateStatus.ValueType  # 0
FW_UPDATE_STATUS_RECEIVING: FwUpdateStatus.ValueType  # 1
FW_UPDATE_STATUS_VERIFYING: FwUpdateStatus.ValueType  # 2
FW_UPDATE_STATUS_BOOT_PENDING: FwUpdateStatus.ValueType  # 3
FW_UPDATE_STATUS_CONFIRMED: FwUpdateStatus.ValueType  # 4
Global___FwUpdateStatus: _TypeAlias = FwUpdateStatus  # noqa: Y015

class _FwChunkStatus:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _FwChunkStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_FwChunkStatus.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    FW_CHUNK_STATUS_OK: _FwChunkStatus.ValueType  # 0
    FW_CHUNK_STATUS_CRC_MISMATCH: _FwChunkStatus.ValueType  # 1
    FW_CHUNK_STATUS_ABORT: _FwChunkStatus.ValueType  # 2

class FwChunkStatus(_FwChunkStatus, metaclass=_FwChunkStatusEnumTypeWrapper): ...

FW_CHUNK_STATUS_OK: FwChunkStatus.ValueType  # 0
FW_CHUNK_STATUS_CRC_MISMATCH: FwChunkStatus.ValueType  # 1
FW_CHUNK_STATUS_ABORT: FwChunkStatus.ValueType  # 2
Global___FwChunkStatus: _TypeAlias = FwChunkStatus  # noqa: Y015

@_typing.final
class Ping(_message.Message):
    """--- Existing messages ---"""

    DESCRIPTOR: _descriptor.Descriptor

    NONCE_FIELD_NUMBER: _builtins.int
    nonce: _builtins.int
    def __init__(
        self,
        *,
        nonce: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["nonce", b"nonce"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Ping: _TypeAlias = Ping  # noqa: Y015

@_typing.final
class Pong(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NONCE_FIELD_NUMBER: _builtins.int
    nonce: _builtins.int
    def __init__(
        self,
        *,
        nonce: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["nonce", b"nonce"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Pong: _TypeAlias = Pong  # noqa: Y015

@_typing.final
class SetSettingsRequest(_message.Message):
    """--- Settings ---"""

    DESCRIPTOR: _descriptor.Descriptor

    LIST_LENGTH_FIELD_NUMBER: _builtins.int
    INTEGRATION_PERIODS_FIELD_NUMBER: _builtins.int
    USE_EMA_FIELD_NUMBER: _builtins.int
    list_length: _builtins.int
    integration_periods: _builtins.int
    use_ema: _builtins.bool
    def __init__(
        self,
        *,
        list_length: _builtins.int = ...,
        integration_periods: _builtins.int = ...,
        use_ema: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["integration_periods", b"integration_periods", "list_length", b"list_length", "use_ema", b"use_ema"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SetSettingsRequest: _TypeAlias = SetSettingsRequest  # noqa: Y015

@_typing.final
class SetSettingsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SetSettingsResponse: _TypeAlias = SetSettingsResponse  # noqa: Y015

@_typing.final
class SetListStartRequest(_message.Message):
    """--- List upload (chunked) ---"""

    DESCRIPTOR: _descriptor.Descriptor

    TOTAL_FLOATS_FIELD_NUMBER: _builtins.int
    total_floats: _builtins.int
    def __init__(
        self,
        *,
        total_floats: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["total_floats", b"total_floats"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SetListStartRequest: _TypeAlias = SetListStartRequest  # noqa: Y015

@_typing.final
class SetListStartResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    READY_FIELD_NUMBER: _builtins.int
    ready: _builtins.bool
    def __init__(
        self,
        *,
        ready: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ready", b"ready"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SetListStartResponse: _TypeAlias = SetListStartResponse  # noqa: Y015

@_typing.final
class ListChunk(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CHUNK_INDEX_FIELD_NUMBER: _builtins.int
    VALUES_FIELD_NUMBER: _builtins.int
    IS_LAST_FIELD_NUMBER: _builtins.int
    chunk_index: _builtins.int
    is_last: _builtins.bool
    @_builtins.property
    def values(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]: ...
    def __init__(
        self,
        *,
        chunk_index: _builtins.int = ...,
        values: _abc.Iterable[_builtins.float] | None = ...,
        is_last: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["chunk_index", b"chunk_index", "is_last", b"is_last", "values", b"values"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListChunk: _TypeAlias = ListChunk  # noqa: Y015

@_typing.final
class SetListCompleteResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    FLOATS_RECEIVED_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    floats_received: _builtins.int
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        floats_received: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["floats_received", b"floats_received", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SetListCompleteResponse: _TypeAlias = SetListCompleteResponse  # noqa: Y015

@_typing.final
class StartScanRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___StartScanRequest: _TypeAlias = StartScanRequest  # noqa: Y015

@_typing.final
class StartScanResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STARTED_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    TRANSFER_MODE_FIELD_NUMBER: _builtins.int
    started: _builtins.bool
    error: _builtins.str
    transfer_mode: Global___TransferMode.ValueType
    def __init__(
        self,
        *,
        started: _builtins.bool = ...,
        error: _builtins.str = ...,
        transfer_mode: Global___TransferMode.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "started", b"started", "transfer_mode", b"transfer_mode"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StartScanResponse: _TypeAlias = StartScanResponse  # noqa: Y015

@_typing.final
class GetResultsRequest(_message.Message):
    """--- Results (chunked) ---"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetResultsRequest: _TypeAlias = GetResultsRequest  # noqa: Y015

@_typing.final
class ResultsChunk(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CHUNK_INDEX_FIELD_NUMBER: _builtins.int
    TIMES_FIELD_NUMBER: _builtins.int
    X_FIELD_NUMBER: _builtins.int
    Y_FIELD_NUMBER: _builtins.int
    IS_LAST_FIELD_NUMBER: _builtins.int
    chunk_index: _builtins.int
    is_last: _builtins.bool
    @_builtins.property
    def times(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]: ...
    @_builtins.property
    def x(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]: ...
    @_builtins.property
    def y(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]: ...
    def __init__(
        self,
        *,
        chunk_index: _builtins.int = ...,
        times: _abc.Iterable[_builtins.float] | None = ...,
        x: _abc.Iterable[_builtins.float] | None = ...,
        y: _abc.Iterable[_builtins.float] | None = ...,
        is_last: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["chunk_index", b"chunk_index", "is_last", b"is_last", "times", b"times", "x", b"x", "y", b"y"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ResultsChunk: _TypeAlias = ResultsChunk  # noqa: Y015

@_typing.final
class GetStatusRequest(_message.Message):
    """--- Status ---"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetStatusRequest: _TypeAlias = GetStatusRequest  # noqa: Y015

@_typing.final
class GetStatusResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SCAN_ONGOING_FIELD_NUMBER: _builtins.int
    LIST_LENGTH_FIELD_NUMBER: _builtins.int
    MAX_LIST_LENGTH_FIELD_NUMBER: _builtins.int
    MODULATION_FREQUENCY_HZ_FIELD_NUMBER: _builtins.int
    SETTINGS_VALID_FIELD_NUMBER: _builtins.int
    LIST_VALID_FIELD_NUMBER: _builtins.int
    scan_ongoing: _builtins.bool
    list_length: _builtins.int
    max_list_length: _builtins.int
    modulation_frequency_hz: _builtins.int
    settings_valid: _builtins.bool
    list_valid: _builtins.bool
    def __init__(
        self,
        *,
        scan_ongoing: _builtins.bool = ...,
        list_length: _builtins.int = ...,
        max_list_length: _builtins.int = ...,
        modulation_frequency_hz: _builtins.int = ...,
        settings_valid: _builtins.bool = ...,
        list_valid: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["list_length", b"list_length", "list_valid", b"list_valid", "max_list_length", b"max_list_length", "modulation_frequency_hz", b"modulation_frequency_hz", "scan_ongoing", b"scan_ongoing", "settings_valid", b"settings_valid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetStatusResponse: _TypeAlias = GetStatusResponse  # noqa: Y015

@_typing.final
class GetDeviceInfoRequest(_message.Message):
    """--- Device Info ---"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetDeviceInfoRequest: _TypeAlias = GetDeviceInfoRequest  # noqa: Y015

@_typing.final
class GetDeviceInfoResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SERIAL_NUMBER_FIELD_NUMBER: _builtins.int
    FIRMWARE_VERSION_FIELD_NUMBER: _builtins.int
    BSP_NAME_FIELD_NUMBER: _builtins.int
    BUILD_TYPE_FIELD_NUMBER: _builtins.int
    TRANSFER_MODE_FIELD_NUMBER: _builtins.int
    HARDWARE_TYPE_FIELD_NUMBER: _builtins.int
    HARDWARE_REVISION_FIELD_NUMBER: _builtins.int
    FIRMWARE_TARGET_FIELD_NUMBER: _builtins.int
    serial_number: _builtins.str
    firmware_version: _builtins.str
    bsp_name: _builtins.str
    build_type: _builtins.str
    transfer_mode: Global___TransferMode.ValueType
    hardware_type: _builtins.str
    hardware_revision: _builtins.int
    firmware_target: _builtins.str
    def __init__(
        self,
        *,
        serial_number: _builtins.str = ...,
        firmware_version: _builtins.str = ...,
        bsp_name: _builtins.str = ...,
        build_type: _builtins.str = ...,
        transfer_mode: Global___TransferMode.ValueType = ...,
        hardware_type: _builtins.str = ...,
        hardware_revision: _builtins.int = ...,
        firmware_target: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bsp_name", b"bsp_name", "build_type", b"build_type", "firmware_target", b"firmware_target", "firmware_version", b"firmware_version", "hardware_revision", b"hardware_revision", "hardware_type", b"hardware_type", "serial_number", b"serial_number", "transfer_mode", b"transfer_mode"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetDeviceInfoResponse: _TypeAlias = GetDeviceInfoResponse  # noqa: Y015

@_typing.final
class RebootRequest(_message.Message):
    """--- Reboot ---"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___RebootRequest: _TypeAlias = RebootRequest  # noqa: Y015

@_typing.final
class GetTransformedListRequest(_message.Message):
    """--- Transformed List (diagnostic) ---"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetTransformedListRequest: _TypeAlias = GetTransformedListRequest  # noqa: Y015

@_typing.final
class TransformedListChunk(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CHUNK_INDEX_FIELD_NUMBER: _builtins.int
    VALUES_FIELD_NUMBER: _builtins.int
    IS_LAST_FIELD_NUMBER: _builtins.int
    chunk_index: _builtins.int
    is_last: _builtins.bool
    @_builtins.property
    def values(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """uint16 stored as uint32 for protobuf"""

    def __init__(
        self,
        *,
        chunk_index: _builtins.int = ...,
        values: _abc.Iterable[_builtins.int] | None = ...,
        is_last: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["chunk_index", b"chunk_index", "is_last", b"is_last", "values", b"values"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TransformedListChunk: _TypeAlias = TransformedListChunk  # noqa: Y015

@_typing.final
class RawCaptureRequest(_message.Message):
    """--- Raw Capture (noise characterization) ---"""

    DESCRIPTOR: _descriptor.Descriptor

    NUM_SAMPLES_FIELD_NUMBER: _builtins.int
    num_samples: _builtins.int
    """Optional, defaults to RAW_CAPTURE_SAMPLES"""
    def __init__(
        self,
        *,
        num_samples: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["num_samples", b"num_samples"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RawCaptureRequest: _TypeAlias = RawCaptureRequest  # noqa: Y015

@_typing.final
class RawCaptureChunk(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CHUNK_INDEX_FIELD_NUMBER: _builtins.int
    SAMPLES_FIELD_NUMBER: _builtins.int
    IS_LAST_FIELD_NUMBER: _builtins.int
    chunk_index: _builtins.int
    is_last: _builtins.bool
    @_builtins.property
    def samples(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """uint16 stored as uint32 for protobuf"""

    def __init__(
        self,
        *,
        chunk_index: _builtins.int = ...,
        samples: _abc.Iterable[_builtins.int] | None = ...,
        is_last: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["chunk_index", b"chunk_index", "is_last", b"is_last", "samples", b"samples"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RawCaptureChunk: _TypeAlias = RawCaptureChunk  # noqa: Y015

@_typing.final
class ResultPoint(_message.Message):
    """--- Per-Point Result Streaming ---"""

    DESCRIPTOR: _descriptor.Descriptor

    POINT_INDEX_FIELD_NUMBER: _builtins.int
    TIME_FIELD_NUMBER: _builtins.int
    X_FIELD_NUMBER: _builtins.int
    Y_FIELD_NUMBER: _builtins.int
    IS_LAST_FIELD_NUMBER: _builtins.int
    SEND_TIMESTAMP_US_FIELD_NUMBER: _builtins.int
    point_index: _builtins.int
    time: _builtins.float
    x: _builtins.float
    y: _builtins.float
    is_last: _builtins.bool
    send_timestamp_us: _builtins.int
    """Firmware microsecond counter when sent"""
    def __init__(
        self,
        *,
        point_index: _builtins.int = ...,
        time: _builtins.float = ...,
        x: _builtins.float = ...,
        y: _builtins.float = ...,
        is_last: _builtins.bool = ...,
        send_timestamp_us: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["is_last", b"is_last", "point_index", b"point_index", "send_timestamp_us", b"send_timestamp_us", "time", b"time", "x", b"x", "y", b"y"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ResultPoint: _TypeAlias = ResultPoint  # noqa: Y015

@_typing.final
class ResultPointNak(_message.Message):
    """--- Reliable Streaming (NAK-based retransmission) ---

    Request retransmission of a specific point (host to device)
    """

    DESCRIPTOR: _descriptor.Descriptor

    POINT_INDEX_FIELD_NUMBER: _builtins.int
    point_index: _builtins.int
    """Index of the missing point to retransmit"""
    def __init__(
        self,
        *,
        point_index: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["point_index", b"point_index"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ResultPointNak: _TypeAlias = ResultPointNak  # noqa: Y015

@_typing.final
class ResultPointRetransmit(_message.Message):
    """Response to NAK - retransmitted point or unavailable notification"""

    DESCRIPTOR: _descriptor.Descriptor

    POINT_INDEX_FIELD_NUMBER: _builtins.int
    AVAILABLE_FIELD_NUMBER: _builtins.int
    TIME_FIELD_NUMBER: _builtins.int
    X_FIELD_NUMBER: _builtins.int
    Y_FIELD_NUMBER: _builtins.int
    point_index: _builtins.int
    """Index of the retransmitted point"""
    available: _builtins.bool
    """False if point aged out of circular buffer"""
    time: _builtins.float
    """Only valid if available=true"""
    x: _builtins.float
    """Only valid if available=true"""
    y: _builtins.float
    """Only valid if available=true"""
    def __init__(
        self,
        *,
        point_index: _builtins.int = ...,
        available: _builtins.bool = ...,
        time: _builtins.float = ...,
        x: _builtins.float = ...,
        y: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["available", b"available", "point_index", b"point_index", "time", b"time", "x", b"x", "y", b"y"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ResultPointRetransmit: _TypeAlias = ResultPointRetransmit  # noqa: Y015

@_typing.final
class ResultsChunkNak(_message.Message):
    """--- Reliable Bulk Transfer (NAK-based retransmission for results chunks) ---

    Request retransmission of a specific results chunk (host to device)
    """

    DESCRIPTOR: _descriptor.Descriptor

    CHUNK_INDEX_FIELD_NUMBER: _builtins.int
    chunk_index: _builtins.int
    """Index of the missing chunk to retransmit"""
    def __init__(
        self,
        *,
        chunk_index: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["chunk_index", b"chunk_index"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ResultsChunkNak: _TypeAlias = ResultsChunkNak  # noqa: Y015

@_typing.final
class ResultsChunkRetransmit(_message.Message):
    """Response to NAK - retransmitted chunk or unavailable notification"""

    DESCRIPTOR: _descriptor.Descriptor

    CHUNK_INDEX_FIELD_NUMBER: _builtins.int
    TIMES_FIELD_NUMBER: _builtins.int
    X_FIELD_NUMBER: _builtins.int
    Y_FIELD_NUMBER: _builtins.int
    IS_LAST_FIELD_NUMBER: _builtins.int
    AVAILABLE_FIELD_NUMBER: _builtins.int
    chunk_index: _builtins.int
    is_last: _builtins.bool
    available: _builtins.bool
    """False if data no longer available"""
    @_builtins.property
    def times(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]: ...
    @_builtins.property
    def x(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]: ...
    @_builtins.property
    def y(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]: ...
    def __init__(
        self,
        *,
        chunk_index: _builtins.int = ...,
        times: _abc.Iterable[_builtins.float] | None = ...,
        x: _abc.Iterable[_builtins.float] | None = ...,
        y: _abc.Iterable[_builtins.float] | None = ...,
        is_last: _builtins.bool = ...,
        available: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["available", b"available", "chunk_index", b"chunk_index", "is_last", b"is_last", "times", b"times", "x", b"x", "y", b"y"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ResultsChunkRetransmit: _TypeAlias = ResultsChunkRetransmit  # noqa: Y015

@_typing.final
class FwUpdateStartRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FIRMWARE_SIZE_FIELD_NUMBER: _builtins.int
    FIRMWARE_CRC_FIELD_NUMBER: _builtins.int
    CHUNK_SIZE_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    firmware_size: _builtins.int
    firmware_crc: _builtins.int
    chunk_size: _builtins.int
    version: _builtins.str
    def __init__(
        self,
        *,
        firmware_size: _builtins.int = ...,
        firmware_crc: _builtins.int = ...,
        chunk_size: _builtins.int = ...,
        version: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["chunk_size", b"chunk_size", "firmware_crc", b"firmware_crc", "firmware_size", b"firmware_size", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FwUpdateStartRequest: _TypeAlias = FwUpdateStartRequest  # noqa: Y015

@_typing.final
class FwUpdateStartResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ACCEPTED_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    accepted: _builtins.bool
    error: _builtins.str
    def __init__(
        self,
        *,
        accepted: _builtins.bool = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["accepted", b"accepted", "error", b"error"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FwUpdateStartResponse: _TypeAlias = FwUpdateStartResponse  # noqa: Y015

@_typing.final
class FwUpdateChunk(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CHUNK_INDEX_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    CHUNK_CRC_FIELD_NUMBER: _builtins.int
    chunk_index: _builtins.int
    data: _builtins.bytes
    chunk_crc: _builtins.int
    def __init__(
        self,
        *,
        chunk_index: _builtins.int = ...,
        data: _builtins.bytes = ...,
        chunk_crc: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["chunk_crc", b"chunk_crc", "chunk_index", b"chunk_index", "data", b"data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FwUpdateChunk: _TypeAlias = FwUpdateChunk  # noqa: Y015

@_typing.final
class FwUpdateChunkAck(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CHUNK_INDEX_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    chunk_index: _builtins.int
    status: Global___FwChunkStatus.ValueType
    def __init__(
        self,
        *,
        chunk_index: _builtins.int = ...,
        status: Global___FwChunkStatus.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["chunk_index", b"chunk_index", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FwUpdateChunkAck: _TypeAlias = FwUpdateChunkAck  # noqa: Y015

@_typing.final
class FwUpdateFinishRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___FwUpdateFinishRequest: _TypeAlias = FwUpdateFinishRequest  # noqa: Y015

@_typing.final
class FwUpdateFinishResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    status: Global___FwUpdateStatus.ValueType
    error: _builtins.str
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        status: Global___FwUpdateStatus.ValueType = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "status", b"status", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FwUpdateFinishResponse: _TypeAlias = FwUpdateFinishResponse  # noqa: Y015

@_typing.final
class FwUpdateStatusRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___FwUpdateStatusRequest: _TypeAlias = FwUpdateStatusRequest  # noqa: Y015

@_typing.final
class FwUpdateStatusResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STATUS_FIELD_NUMBER: _builtins.int
    CHUNKS_RECEIVED_FIELD_NUMBER: _builtins.int
    TOTAL_CHUNKS_FIELD_NUMBER: _builtins.int
    BYTES_RECEIVED_FIELD_NUMBER: _builtins.int
    status: Global___FwUpdateStatus.ValueType
    chunks_received: _builtins.int
    total_chunks: _builtins.int
    bytes_received: _builtins.int
    def __init__(
        self,
        *,
        status: Global___FwUpdateStatus.ValueType = ...,
        chunks_received: _builtins.int = ...,
        total_chunks: _builtins.int = ...,
        bytes_received: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bytes_received", b"bytes_received", "chunks_received", b"chunks_received", "status", b"status", "total_chunks", b"total_chunks"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FwUpdateStatusResponse: _TypeAlias = FwUpdateStatusResponse  # noqa: Y015

@_typing.final
class FwBootConfirmRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___FwBootConfirmRequest: _TypeAlias = FwBootConfirmRequest  # noqa: Y015

@_typing.final
class FwBootConfirmResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONFIRMED_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    confirmed: _builtins.bool
    version: _builtins.str
    def __init__(
        self,
        *,
        confirmed: _builtins.bool = ...,
        version: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["confirmed", b"confirmed", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FwBootConfirmResponse: _TypeAlias = FwBootConfirmResponse  # noqa: Y015

@_typing.final
class Envelope(_message.Message):
    """--- Envelope ---"""

    DESCRIPTOR: _descriptor.Descriptor

    SEQ_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    PING_FIELD_NUMBER: _builtins.int
    PONG_FIELD_NUMBER: _builtins.int
    SET_SETTINGS_REQUEST_FIELD_NUMBER: _builtins.int
    SET_SETTINGS_RESPONSE_FIELD_NUMBER: _builtins.int
    SET_LIST_START_REQUEST_FIELD_NUMBER: _builtins.int
    SET_LIST_START_RESPONSE_FIELD_NUMBER: _builtins.int
    LIST_CHUNK_FIELD_NUMBER: _builtins.int
    SET_LIST_COMPLETE_RESPONSE_FIELD_NUMBER: _builtins.int
    START_SCAN_REQUEST_FIELD_NUMBER: _builtins.int
    START_SCAN_RESPONSE_FIELD_NUMBER: _builtins.int
    GET_RESULTS_REQUEST_FIELD_NUMBER: _builtins.int
    RESULTS_CHUNK_FIELD_NUMBER: _builtins.int
    GET_STATUS_REQUEST_FIELD_NUMBER: _builtins.int
    GET_STATUS_RESPONSE_FIELD_NUMBER: _builtins.int
    REBOOT_REQUEST_FIELD_NUMBER: _builtins.int
    GET_TRANSFORMED_LIST_REQUEST_FIELD_NUMBER: _builtins.int
    TRANSFORMED_LIST_CHUNK_FIELD_NUMBER: _builtins.int
    GET_DEVICE_INFO_REQUEST_FIELD_NUMBER: _builtins.int
    GET_DEVICE_INFO_RESPONSE_FIELD_NUMBER: _builtins.int
    RAW_CAPTURE_REQUEST_FIELD_NUMBER: _builtins.int
    RAW_CAPTURE_CHUNK_FIELD_NUMBER: _builtins.int
    RESULT_POINT_FIELD_NUMBER: _builtins.int
    RESULT_POINT_NAK_FIELD_NUMBER: _builtins.int
    RESULT_POINT_RETRANSMIT_FIELD_NUMBER: _builtins.int
    FW_UPDATE_START_REQUEST_FIELD_NUMBER: _builtins.int
    FW_UPDATE_START_RESPONSE_FIELD_NUMBER: _builtins.int
    FW_UPDATE_CHUNK_FIELD_NUMBER: _builtins.int
    FW_UPDATE_CHUNK_ACK_FIELD_NUMBER: _builtins.int
    FW_UPDATE_FINISH_REQUEST_FIELD_NUMBER: _builtins.int
    FW_UPDATE_FINISH_RESPONSE_FIELD_NUMBER: _builtins.int
    FW_UPDATE_STATUS_REQUEST_FIELD_NUMBER: _builtins.int
    FW_UPDATE_STATUS_RESPONSE_FIELD_NUMBER: _builtins.int
    FW_BOOT_CONFIRM_REQUEST_FIELD_NUMBER: _builtins.int
    FW_BOOT_CONFIRM_RESPONSE_FIELD_NUMBER: _builtins.int
    RESULTS_CHUNK_NAK_FIELD_NUMBER: _builtins.int
    RESULTS_CHUNK_RETRANSMIT_FIELD_NUMBER: _builtins.int
    seq: _builtins.int
    type: Global___MsgType.ValueType
    @_builtins.property
    def ping(self) -> Global___Ping:
        """Existing"""

    @_builtins.property
    def pong(self) -> Global___Pong: ...
    @_builtins.property
    def set_settings_request(self) -> Global___SetSettingsRequest:
        """Settings"""

    @_builtins.property
    def set_settings_response(self) -> Global___SetSettingsResponse: ...
    @_builtins.property
    def set_list_start_request(self) -> Global___SetListStartRequest:
        """List upload"""

    @_builtins.property
    def set_list_start_response(self) -> Global___SetListStartResponse: ...
    @_builtins.property
    def list_chunk(self) -> Global___ListChunk: ...
    @_builtins.property
    def set_list_complete_response(self) -> Global___SetListCompleteResponse: ...
    @_builtins.property
    def start_scan_request(self) -> Global___StartScanRequest:
        """Scan"""

    @_builtins.property
    def start_scan_response(self) -> Global___StartScanResponse: ...
    @_builtins.property
    def get_results_request(self) -> Global___GetResultsRequest:
        """Results"""

    @_builtins.property
    def results_chunk(self) -> Global___ResultsChunk: ...
    @_builtins.property
    def get_status_request(self) -> Global___GetStatusRequest:
        """Status"""

    @_builtins.property
    def get_status_response(self) -> Global___GetStatusResponse: ...
    @_builtins.property
    def reboot_request(self) -> Global___RebootRequest:
        """Reboot"""

    @_builtins.property
    def get_transformed_list_request(self) -> Global___GetTransformedListRequest:
        """Transformed list"""

    @_builtins.property
    def transformed_list_chunk(self) -> Global___TransformedListChunk: ...
    @_builtins.property
    def get_device_info_request(self) -> Global___GetDeviceInfoRequest:
        """Device info"""

    @_builtins.property
    def get_device_info_response(self) -> Global___GetDeviceInfoResponse: ...
    @_builtins.property
    def raw_capture_request(self) -> Global___RawCaptureRequest:
        """Raw capture"""

    @_builtins.property
    def raw_capture_chunk(self) -> Global___RawCaptureChunk: ...
    @_builtins.property
    def result_point(self) -> Global___ResultPoint:
        """Per-point result streaming"""

    @_builtins.property
    def result_point_nak(self) -> Global___ResultPointNak:
        """Reliable streaming (NAK-based retransmission)"""

    @_builtins.property
    def result_point_retransmit(self) -> Global___ResultPointRetransmit: ...
    @_builtins.property
    def fw_update_start_request(self) -> Global___FwUpdateStartRequest:
        """Firmware update"""

    @_builtins.property
    def fw_update_start_response(self) -> Global___FwUpdateStartResponse: ...
    @_builtins.property
    def fw_update_chunk(self) -> Global___FwUpdateChunk: ...
    @_builtins.property
    def fw_update_chunk_ack(self) -> Global___FwUpdateChunkAck: ...
    @_builtins.property
    def fw_update_finish_request(self) -> Global___FwUpdateFinishRequest: ...
    @_builtins.property
    def fw_update_finish_response(self) -> Global___FwUpdateFinishResponse: ...
    @_builtins.property
    def fw_update_status_request(self) -> Global___FwUpdateStatusRequest: ...
    @_builtins.property
    def fw_update_status_response(self) -> Global___FwUpdateStatusResponse: ...
    @_builtins.property
    def fw_boot_confirm_request(self) -> Global___FwBootConfirmRequest: ...
    @_builtins.property
    def fw_boot_confirm_response(self) -> Global___FwBootConfirmResponse: ...
    @_builtins.property
    def results_chunk_nak(self) -> Global___ResultsChunkNak:
        """Reliable bulk transfer (NAK-based retransmission for results chunks)"""

    @_builtins.property
    def results_chunk_retransmit(self) -> Global___ResultsChunkRetransmit: ...
    def __init__(
        self,
        *,
        seq: _builtins.int = ...,
        type: Global___MsgType.ValueType = ...,
        ping: Global___Ping | None = ...,
        pong: Global___Pong | None = ...,
        set_settings_request: Global___SetSettingsRequest | None = ...,
        set_settings_response: Global___SetSettingsResponse | None = ...,
        set_list_start_request: Global___SetListStartRequest | None = ...,
        set_list_start_response: Global___SetListStartResponse | None = ...,
        list_chunk: Global___ListChunk | None = ...,
        set_list_complete_response: Global___SetListCompleteResponse | None = ...,
        start_scan_request: Global___StartScanRequest | None = ...,
        start_scan_response: Global___StartScanResponse | None = ...,
        get_results_request: Global___GetResultsRequest | None = ...,
        results_chunk: Global___ResultsChunk | None = ...,
        get_status_request: Global___GetStatusRequest | None = ...,
        get_status_response: Global___GetStatusResponse | None = ...,
        reboot_request: Global___RebootRequest | None = ...,
        get_transformed_list_request: Global___GetTransformedListRequest | None = ...,
        transformed_list_chunk: Global___TransformedListChunk | None = ...,
        get_device_info_request: Global___GetDeviceInfoRequest | None = ...,
        get_device_info_response: Global___GetDeviceInfoResponse | None = ...,
        raw_capture_request: Global___RawCaptureRequest | None = ...,
        raw_capture_chunk: Global___RawCaptureChunk | None = ...,
        result_point: Global___ResultPoint | None = ...,
        result_point_nak: Global___ResultPointNak | None = ...,
        result_point_retransmit: Global___ResultPointRetransmit | None = ...,
        fw_update_start_request: Global___FwUpdateStartRequest | None = ...,
        fw_update_start_response: Global___FwUpdateStartResponse | None = ...,
        fw_update_chunk: Global___FwUpdateChunk | None = ...,
        fw_update_chunk_ack: Global___FwUpdateChunkAck | None = ...,
        fw_update_finish_request: Global___FwUpdateFinishRequest | None = ...,
        fw_update_finish_response: Global___FwUpdateFinishResponse | None = ...,
        fw_update_status_request: Global___FwUpdateStatusRequest | None = ...,
        fw_update_status_response: Global___FwUpdateStatusResponse | None = ...,
        fw_boot_confirm_request: Global___FwBootConfirmRequest | None = ...,
        fw_boot_confirm_response: Global___FwBootConfirmResponse | None = ...,
        results_chunk_nak: Global___ResultsChunkNak | None = ...,
        results_chunk_retransmit: Global___ResultsChunkRetransmit | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["fw_boot_confirm_request", b"fw_boot_confirm_request", "fw_boot_confirm_response", b"fw_boot_confirm_response", "fw_update_chunk", b"fw_update_chunk", "fw_update_chunk_ack", b"fw_update_chunk_ack", "fw_update_finish_request", b"fw_update_finish_request", "fw_update_finish_response", b"fw_update_finish_response", "fw_update_start_request", b"fw_update_start_request", "fw_update_start_response", b"fw_update_start_response", "fw_update_status_request", b"fw_update_status_request", "fw_update_status_response", b"fw_update_status_response", "get_device_info_request", b"get_device_info_request", "get_device_info_response", b"get_device_info_response", "get_results_request", b"get_results_request", "get_status_request", b"get_status_request", "get_status_response", b"get_status_response", "get_transformed_list_request", b"get_transformed_list_request", "list_chunk", b"list_chunk", "payload", b"payload", "ping", b"ping", "pong", b"pong", "raw_capture_chunk", b"raw_capture_chunk", "raw_capture_request", b"raw_capture_request", "reboot_request", b"reboot_request", "result_point", b"result_point", "result_point_nak", b"result_point_nak", "result_point_retransmit", b"result_point_retransmit", "results_chunk", b"results_chunk", "results_chunk_nak", b"results_chunk_nak", "results_chunk_retransmit", b"results_chunk_retransmit", "set_list_complete_response", b"set_list_complete_response", "set_list_start_request", b"set_list_start_request", "set_list_start_response", b"set_list_start_response", "set_settings_request", b"set_settings_request", "set_settings_response", b"set_settings_response", "start_scan_request", b"start_scan_request", "start_scan_response", b"start_scan_response", "transformed_list_chunk", b"transformed_list_chunk"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fw_boot_confirm_request", b"fw_boot_confirm_request", "fw_boot_confirm_response", b"fw_boot_confirm_response", "fw_update_chunk", b"fw_update_chunk", "fw_update_chunk_ack", b"fw_update_chunk_ack", "fw_update_finish_request", b"fw_update_finish_request", "fw_update_finish_response", b"fw_update_finish_response", "fw_update_start_request", b"fw_update_start_request", "fw_update_start_response", b"fw_update_start_response", "fw_update_status_request", b"fw_update_status_request", "fw_update_status_response", b"fw_update_status_response", "get_device_info_request", b"get_device_info_request", "get_device_info_response", b"get_device_info_response", "get_results_request", b"get_results_request", "get_status_request", b"get_status_request", "get_status_response", b"get_status_response", "get_transformed_list_request", b"get_transformed_list_request", "list_chunk", b"list_chunk", "payload", b"payload", "ping", b"ping", "pong", b"pong", "raw_capture_chunk", b"raw_capture_chunk", "raw_capture_request", b"raw_capture_request", "reboot_request", b"reboot_request", "result_point", b"result_point", "result_point_nak", b"result_point_nak", "result_point_retransmit", b"result_point_retransmit", "results_chunk", b"results_chunk", "results_chunk_nak", b"results_chunk_nak", "results_chunk_retransmit", b"results_chunk_retransmit", "seq", b"seq", "set_list_complete_response", b"set_list_complete_response", "set_list_start_request", b"set_list_start_request", "set_list_start_response", b"set_list_start_response", "set_settings_request", b"set_settings_request", "set_settings_response", b"set_settings_response", "start_scan_request", b"start_scan_request", "start_scan_response", b"start_scan_response", "transformed_list_chunk", b"transformed_list_chunk", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal["ping", "pong", "set_settings_request", "set_settings_response", "set_list_start_request", "set_list_start_response", "list_chunk", "set_list_complete_response", "start_scan_request", "start_scan_response", "get_results_request", "results_chunk", "get_status_request", "get_status_response", "reboot_request", "get_transformed_list_request", "transformed_list_chunk", "get_device_info_request", "get_device_info_response", "raw_capture_request", "raw_capture_chunk", "result_point", "result_point_nak", "result_point_retransmit", "fw_update_start_request", "fw_update_start_response", "fw_update_chunk", "fw_update_chunk_ack", "fw_update_finish_request", "fw_update_finish_response", "fw_update_status_request", "fw_update_status_response", "fw_boot_confirm_request", "fw_boot_confirm_response", "results_chunk_nak", "results_chunk_retransmit"]  # noqa: Y015
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal["payload", b"payload"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None: ...

Global___Envelope: _TypeAlias = Envelope  # noqa: Y015
