/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_COMM_ENVELOPE_PB_H_INCLUDED
#define PB_COMM_ENVELOPE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _comm_MsgType {
    comm_MsgType_MSG_TYPE_UNKNOWN = 0,
    comm_MsgType_MSG_TYPE_PING = 1,
    comm_MsgType_MSG_TYPE_PONG = 2,
    /* Settings */
    comm_MsgType_MSG_TYPE_SET_SETTINGS_REQUEST = 3,
    comm_MsgType_MSG_TYPE_SET_SETTINGS_RESPONSE = 4,
    /* List upload (chunked) */
    comm_MsgType_MSG_TYPE_SET_LIST_START_REQUEST = 5,
    comm_MsgType_MSG_TYPE_SET_LIST_START_RESPONSE = 6,
    comm_MsgType_MSG_TYPE_LIST_CHUNK = 7,
    comm_MsgType_MSG_TYPE_SET_LIST_COMPLETE_RESPONSE = 8,
    /* Scan */
    comm_MsgType_MSG_TYPE_START_SCAN_REQUEST = 9,
    comm_MsgType_MSG_TYPE_START_SCAN_RESPONSE = 10,
    /* Results (chunked) */
    comm_MsgType_MSG_TYPE_GET_RESULTS_REQUEST = 11,
    comm_MsgType_MSG_TYPE_RESULTS_CHUNK = 12,
    /* Status */
    comm_MsgType_MSG_TYPE_GET_STATUS_REQUEST = 13,
    comm_MsgType_MSG_TYPE_GET_STATUS_RESPONSE = 14,
    /* Device info */
    comm_MsgType_MSG_TYPE_GET_SERIAL_REQUEST = 15,
    comm_MsgType_MSG_TYPE_GET_SERIAL_RESPONSE = 16,
    comm_MsgType_MSG_TYPE_GET_VERSION_REQUEST = 17,
    comm_MsgType_MSG_TYPE_GET_VERSION_RESPONSE = 18,
    /* Reboot */
    comm_MsgType_MSG_TYPE_REBOOT_REQUEST = 19,
    /* Transformed list (diagnostic) */
    comm_MsgType_MSG_TYPE_GET_TRANSFORMED_LIST_REQUEST = 20,
    comm_MsgType_MSG_TYPE_TRANSFORMED_LIST_CHUNK = 21,
    /* Capabilities */
    comm_MsgType_MSG_TYPE_GET_CAPABILITIES_REQUEST = 22,
    comm_MsgType_MSG_TYPE_GET_CAPABILITIES_RESPONSE = 23,
    /* Raw capture (noise characterization) */
    comm_MsgType_MSG_TYPE_RAW_CAPTURE_REQUEST = 24,
    comm_MsgType_MSG_TYPE_RAW_CAPTURE_CHUNK = 25,
    /* Per-point result streaming */
    comm_MsgType_MSG_TYPE_RESULT_POINT = 26,
    /* Reliable streaming (NAK-based retransmission) */
    comm_MsgType_MSG_TYPE_RESULT_POINT_NAK = 27,
    comm_MsgType_MSG_TYPE_RESULT_POINT_RETRANSMIT = 28,
    /* Firmware update */
    comm_MsgType_MSG_TYPE_FW_UPDATE_START_REQUEST = 29,
    comm_MsgType_MSG_TYPE_FW_UPDATE_START_RESPONSE = 30,
    comm_MsgType_MSG_TYPE_FW_UPDATE_CHUNK = 31,
    comm_MsgType_MSG_TYPE_FW_UPDATE_CHUNK_ACK = 32,
    comm_MsgType_MSG_TYPE_FW_UPDATE_FINISH_REQUEST = 33,
    comm_MsgType_MSG_TYPE_FW_UPDATE_FINISH_RESPONSE = 34,
    comm_MsgType_MSG_TYPE_FW_UPDATE_STATUS_REQUEST = 35,
    comm_MsgType_MSG_TYPE_FW_UPDATE_STATUS_RESPONSE = 36,
    comm_MsgType_MSG_TYPE_FW_BOOT_CONFIRM_REQUEST = 37,
    comm_MsgType_MSG_TYPE_FW_BOOT_CONFIRM_RESPONSE = 38,
    /* Reliable bulk transfer (NAK-based retransmission for results chunks) */
    comm_MsgType_MSG_TYPE_RESULTS_CHUNK_NAK = 39,
    comm_MsgType_MSG_TYPE_RESULTS_CHUNK_RETRANSMIT = 40
} comm_MsgType;

typedef enum _comm_TransferMode {
    comm_TransferMode_TRANSFER_MODE_BULK = 0,
    comm_TransferMode_TRANSFER_MODE_PER_POINT = 1
} comm_TransferMode;

typedef enum _comm_FwUpdateStatus {
    comm_FwUpdateStatus_FW_UPDATE_STATUS_IDLE = 0,
    comm_FwUpdateStatus_FW_UPDATE_STATUS_RECEIVING = 1,
    comm_FwUpdateStatus_FW_UPDATE_STATUS_VERIFYING = 2,
    comm_FwUpdateStatus_FW_UPDATE_STATUS_BOOT_PENDING = 3,
    comm_FwUpdateStatus_FW_UPDATE_STATUS_CONFIRMED = 4
} comm_FwUpdateStatus;

typedef enum _comm_FwChunkStatus {
    comm_FwChunkStatus_FW_CHUNK_STATUS_OK = 0,
    comm_FwChunkStatus_FW_CHUNK_STATUS_CRC_MISMATCH = 1,
    comm_FwChunkStatus_FW_CHUNK_STATUS_ABORT = 2
} comm_FwChunkStatus;

/* Struct definitions */
typedef struct _comm_Ping {
    uint32_t nonce;
} comm_Ping;

typedef struct _comm_Pong {
    uint32_t nonce;
} comm_Pong;

typedef struct _comm_SetSettingsRequest {
    uint32_t list_length;
    uint32_t integration_periods;
    bool use_ema;
} comm_SetSettingsRequest;

typedef struct _comm_SetSettingsResponse {
    bool success;
} comm_SetSettingsResponse;

typedef struct _comm_SetListStartRequest {
    uint32_t total_floats;
} comm_SetListStartRequest;

typedef struct _comm_SetListStartResponse {
    bool ready;
} comm_SetListStartResponse;

typedef struct _comm_ListChunk {
    uint32_t chunk_index;
    pb_callback_t values;
    bool is_last;
} comm_ListChunk;

typedef struct _comm_SetListCompleteResponse {
    bool success;
    uint32_t floats_received;
} comm_SetListCompleteResponse;

typedef struct _comm_StartScanRequest {
    char dummy_field;
} comm_StartScanRequest;

typedef struct _comm_StartScanResponse {
    bool started;
    pb_callback_t error;
    comm_TransferMode transfer_mode;
} comm_StartScanResponse;

typedef struct _comm_GetResultsRequest {
    char dummy_field;
} comm_GetResultsRequest;

typedef struct _comm_ResultsChunk {
    uint32_t chunk_index;
    pb_callback_t times;
    pb_callback_t x;
    pb_callback_t y;
    bool is_last;
} comm_ResultsChunk;

typedef struct _comm_GetStatusRequest {
    char dummy_field;
} comm_GetStatusRequest;

typedef struct _comm_GetStatusResponse {
    bool scan_ongoing;
    uint32_t list_length;
    uint32_t max_list_length;
    uint32_t modulation_frequency_hz;
    bool settings_valid;
    bool list_valid;
} comm_GetStatusResponse;

typedef struct _comm_GetSerialRequest {
    char dummy_field;
} comm_GetSerialRequest;

typedef struct _comm_GetSerialResponse {
    pb_callback_t serial;
} comm_GetSerialResponse;

typedef struct _comm_GetVersionRequest {
    char dummy_field;
} comm_GetVersionRequest;

typedef struct _comm_GetVersionResponse {
    pb_callback_t version;
} comm_GetVersionResponse;

typedef struct _comm_RebootRequest {
    char dummy_field;
} comm_RebootRequest;

typedef struct _comm_GetTransformedListRequest {
    char dummy_field;
} comm_GetTransformedListRequest;

typedef struct _comm_TransformedListChunk {
    uint32_t chunk_index;
    pb_callback_t values; /* uint16 stored as uint32 for protobuf */
    bool is_last;
} comm_TransformedListChunk;

typedef struct _comm_GetCapabilitiesRequest {
    char dummy_field;
} comm_GetCapabilitiesRequest;

typedef struct _comm_GetCapabilitiesResponse {
    bool has_external_dac;
    bool has_encoder;
    bool has_i2c1;
    bool has_i2c2;
    bool has_i2c3;
    bool has_power_rails;
} comm_GetCapabilitiesResponse;

typedef struct _comm_RawCaptureRequest {
    uint32_t num_samples; /* Optional, defaults to RAW_CAPTURE_SAMPLES */
} comm_RawCaptureRequest;

typedef struct _comm_RawCaptureChunk {
    uint32_t chunk_index;
    pb_callback_t samples; /* uint16 stored as uint32 for protobuf */
    bool is_last;
} comm_RawCaptureChunk;

typedef struct _comm_ResultPoint {
    uint32_t point_index;
    float time;
    float x;
    float y;
    bool is_last;
    uint32_t send_timestamp_us; /* Firmware microsecond counter when sent */
} comm_ResultPoint;

/* Request retransmission of a specific point (host to device) */
typedef struct _comm_ResultPointNak {
    uint32_t point_index; /* Index of the missing point to retransmit */
} comm_ResultPointNak;

/* Response to NAK - retransmitted point or unavailable notification */
typedef struct _comm_ResultPointRetransmit {
    uint32_t point_index; /* Index of the retransmitted point */
    bool available; /* False if point aged out of circular buffer */
    float time; /* Only valid if available=true */
    float x; /* Only valid if available=true */
    float y; /* Only valid if available=true */
} comm_ResultPointRetransmit;

/* Request retransmission of a specific results chunk (host to device) */
typedef struct _comm_ResultsChunkNak {
    uint32_t chunk_index; /* Index of the missing chunk to retransmit */
} comm_ResultsChunkNak;

/* Response to NAK - retransmitted chunk or unavailable notification */
typedef struct _comm_ResultsChunkRetransmit {
    uint32_t chunk_index;
    pb_callback_t times;
    pb_callback_t x;
    pb_callback_t y;
    bool is_last;
    bool available; /* False if data no longer available */
} comm_ResultsChunkRetransmit;

typedef struct _comm_FwUpdateStartRequest {
    uint32_t firmware_size;
    uint32_t firmware_crc;
    uint32_t chunk_size;
    pb_callback_t version;
} comm_FwUpdateStartRequest;

typedef struct _comm_FwUpdateStartResponse {
    bool accepted;
    pb_callback_t error;
} comm_FwUpdateStartResponse;

typedef struct _comm_FwUpdateChunk {
    uint32_t chunk_index;
    pb_callback_t data;
    uint32_t chunk_crc;
} comm_FwUpdateChunk;

typedef struct _comm_FwUpdateChunkAck {
    uint32_t chunk_index;
    comm_FwChunkStatus status;
} comm_FwUpdateChunkAck;

typedef struct _comm_FwUpdateFinishRequest {
    char dummy_field;
} comm_FwUpdateFinishRequest;

typedef struct _comm_FwUpdateFinishResponse {
    bool success;
    comm_FwUpdateStatus status;
    pb_callback_t error;
} comm_FwUpdateFinishResponse;

typedef struct _comm_FwUpdateStatusRequest {
    char dummy_field;
} comm_FwUpdateStatusRequest;

typedef struct _comm_FwUpdateStatusResponse {
    comm_FwUpdateStatus status;
    uint32_t chunks_received;
    uint32_t total_chunks;
    uint32_t bytes_received;
} comm_FwUpdateStatusResponse;

typedef struct _comm_FwBootConfirmRequest {
    char dummy_field;
} comm_FwBootConfirmRequest;

typedef struct _comm_FwBootConfirmResponse {
    bool confirmed;
    pb_callback_t version;
} comm_FwBootConfirmResponse;

typedef struct _comm_Envelope {
    uint32_t seq;
    comm_MsgType type;
    pb_size_t which_payload;
    union {
        /* Existing */
        comm_Ping ping;
        comm_Pong pong;
        /* Settings */
        comm_SetSettingsRequest set_settings_request;
        comm_SetSettingsResponse set_settings_response;
        /* List upload */
        comm_SetListStartRequest set_list_start_request;
        comm_SetListStartResponse set_list_start_response;
        comm_ListChunk list_chunk;
        comm_SetListCompleteResponse set_list_complete_response;
        /* Scan */
        comm_StartScanRequest start_scan_request;
        comm_StartScanResponse start_scan_response;
        /* Results */
        comm_GetResultsRequest get_results_request;
        comm_ResultsChunk results_chunk;
        /* Status */
        comm_GetStatusRequest get_status_request;
        comm_GetStatusResponse get_status_response;
        /* Device info */
        comm_GetSerialRequest get_serial_request;
        comm_GetSerialResponse get_serial_response;
        comm_GetVersionRequest get_version_request;
        comm_GetVersionResponse get_version_response;
        /* Reboot */
        comm_RebootRequest reboot_request;
        /* Transformed list */
        comm_GetTransformedListRequest get_transformed_list_request;
        comm_TransformedListChunk transformed_list_chunk;
        /* Capabilities */
        comm_GetCapabilitiesRequest get_capabilities_request;
        comm_GetCapabilitiesResponse get_capabilities_response;
        /* Raw capture */
        comm_RawCaptureRequest raw_capture_request;
        comm_RawCaptureChunk raw_capture_chunk;
        /* Per-point result streaming */
        comm_ResultPoint result_point;
        /* Reliable streaming (NAK-based retransmission) */
        comm_ResultPointNak result_point_nak;
        comm_ResultPointRetransmit result_point_retransmit;
        /* Firmware update */
        comm_FwUpdateStartRequest fw_update_start_request;
        comm_FwUpdateStartResponse fw_update_start_response;
        comm_FwUpdateChunk fw_update_chunk;
        comm_FwUpdateChunkAck fw_update_chunk_ack;
        comm_FwUpdateFinishRequest fw_update_finish_request;
        comm_FwUpdateFinishResponse fw_update_finish_response;
        comm_FwUpdateStatusRequest fw_update_status_request;
        comm_FwUpdateStatusResponse fw_update_status_response;
        comm_FwBootConfirmRequest fw_boot_confirm_request;
        comm_FwBootConfirmResponse fw_boot_confirm_response;
        /* Reliable bulk transfer (NAK-based retransmission for results chunks) */
        comm_ResultsChunkNak results_chunk_nak;
        comm_ResultsChunkRetransmit results_chunk_retransmit;
    } payload;
} comm_Envelope;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _comm_MsgType_MIN comm_MsgType_MSG_TYPE_UNKNOWN
#define _comm_MsgType_MAX comm_MsgType_MSG_TYPE_RESULTS_CHUNK_RETRANSMIT
#define _comm_MsgType_ARRAYSIZE ((comm_MsgType)(comm_MsgType_MSG_TYPE_RESULTS_CHUNK_RETRANSMIT+1))

#define _comm_TransferMode_MIN comm_TransferMode_TRANSFER_MODE_BULK
#define _comm_TransferMode_MAX comm_TransferMode_TRANSFER_MODE_PER_POINT
#define _comm_TransferMode_ARRAYSIZE ((comm_TransferMode)(comm_TransferMode_TRANSFER_MODE_PER_POINT+1))

#define _comm_FwUpdateStatus_MIN comm_FwUpdateStatus_FW_UPDATE_STATUS_IDLE
#define _comm_FwUpdateStatus_MAX comm_FwUpdateStatus_FW_UPDATE_STATUS_CONFIRMED
#define _comm_FwUpdateStatus_ARRAYSIZE ((comm_FwUpdateStatus)(comm_FwUpdateStatus_FW_UPDATE_STATUS_CONFIRMED+1))

#define _comm_FwChunkStatus_MIN comm_FwChunkStatus_FW_CHUNK_STATUS_OK
#define _comm_FwChunkStatus_MAX comm_FwChunkStatus_FW_CHUNK_STATUS_ABORT
#define _comm_FwChunkStatus_ARRAYSIZE ((comm_FwChunkStatus)(comm_FwChunkStatus_FW_CHUNK_STATUS_ABORT+1))










#define comm_StartScanResponse_transfer_mode_ENUMTYPE comm_TransferMode
























#define comm_FwUpdateChunkAck_status_ENUMTYPE comm_FwChunkStatus


#define comm_FwUpdateFinishResponse_status_ENUMTYPE comm_FwUpdateStatus


#define comm_FwUpdateStatusResponse_status_ENUMTYPE comm_FwUpdateStatus



#define comm_Envelope_type_ENUMTYPE comm_MsgType


/* Initializer values for message structs */
#define comm_Ping_init_default                   {0}
#define comm_Pong_init_default                   {0}
#define comm_SetSettingsRequest_init_default     {0, 0, 0}
#define comm_SetSettingsResponse_init_default    {0}
#define comm_SetListStartRequest_init_default    {0}
#define comm_SetListStartResponse_init_default   {0}
#define comm_ListChunk_init_default              {0, {{NULL}, NULL}, 0}
#define comm_SetListCompleteResponse_init_default {0, 0}
#define comm_StartScanRequest_init_default       {0}
#define comm_StartScanResponse_init_default      {0, {{NULL}, NULL}, _comm_TransferMode_MIN}
#define comm_GetResultsRequest_init_default      {0}
#define comm_ResultsChunk_init_default           {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define comm_GetStatusRequest_init_default       {0}
#define comm_GetStatusResponse_init_default      {0, 0, 0, 0, 0, 0}
#define comm_GetSerialRequest_init_default       {0}
#define comm_GetSerialResponse_init_default      {{{NULL}, NULL}}
#define comm_GetVersionRequest_init_default      {0}
#define comm_GetVersionResponse_init_default     {{{NULL}, NULL}}
#define comm_RebootRequest_init_default          {0}
#define comm_GetTransformedListRequest_init_default {0}
#define comm_TransformedListChunk_init_default   {0, {{NULL}, NULL}, 0}
#define comm_GetCapabilitiesRequest_init_default {0}
#define comm_GetCapabilitiesResponse_init_default {0, 0, 0, 0, 0, 0}
#define comm_RawCaptureRequest_init_default      {0}
#define comm_RawCaptureChunk_init_default        {0, {{NULL}, NULL}, 0}
#define comm_ResultPoint_init_default            {0, 0, 0, 0, 0, 0}
#define comm_ResultPointNak_init_default         {0}
#define comm_ResultPointRetransmit_init_default  {0, 0, 0, 0, 0}
#define comm_ResultsChunkNak_init_default        {0}
#define comm_ResultsChunkRetransmit_init_default {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0}
#define comm_FwUpdateStartRequest_init_default   {0, 0, 0, {{NULL}, NULL}}
#define comm_FwUpdateStartResponse_init_default  {0, {{NULL}, NULL}}
#define comm_FwUpdateChunk_init_default          {0, {{NULL}, NULL}, 0}
#define comm_FwUpdateChunkAck_init_default       {0, _comm_FwChunkStatus_MIN}
#define comm_FwUpdateFinishRequest_init_default  {0}
#define comm_FwUpdateFinishResponse_init_default {0, _comm_FwUpdateStatus_MIN, {{NULL}, NULL}}
#define comm_FwUpdateStatusRequest_init_default  {0}
#define comm_FwUpdateStatusResponse_init_default {_comm_FwUpdateStatus_MIN, 0, 0, 0}
#define comm_FwBootConfirmRequest_init_default   {0}
#define comm_FwBootConfirmResponse_init_default  {0, {{NULL}, NULL}}
#define comm_Envelope_init_default               {0, _comm_MsgType_MIN, 0, {comm_Ping_init_default}}
#define comm_Ping_init_zero                      {0}
#define comm_Pong_init_zero                      {0}
#define comm_SetSettingsRequest_init_zero        {0, 0, 0}
#define comm_SetSettingsResponse_init_zero       {0}
#define comm_SetListStartRequest_init_zero       {0}
#define comm_SetListStartResponse_init_zero      {0}
#define comm_ListChunk_init_zero                 {0, {{NULL}, NULL}, 0}
#define comm_SetListCompleteResponse_init_zero   {0, 0}
#define comm_StartScanRequest_init_zero          {0}
#define comm_StartScanResponse_init_zero         {0, {{NULL}, NULL}, _comm_TransferMode_MIN}
#define comm_GetResultsRequest_init_zero         {0}
#define comm_ResultsChunk_init_zero              {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define comm_GetStatusRequest_init_zero          {0}
#define comm_GetStatusResponse_init_zero         {0, 0, 0, 0, 0, 0}
#define comm_GetSerialRequest_init_zero          {0}
#define comm_GetSerialResponse_init_zero         {{{NULL}, NULL}}
#define comm_GetVersionRequest_init_zero         {0}
#define comm_GetVersionResponse_init_zero        {{{NULL}, NULL}}
#define comm_RebootRequest_init_zero             {0}
#define comm_GetTransformedListRequest_init_zero {0}
#define comm_TransformedListChunk_init_zero      {0, {{NULL}, NULL}, 0}
#define comm_GetCapabilitiesRequest_init_zero    {0}
#define comm_GetCapabilitiesResponse_init_zero   {0, 0, 0, 0, 0, 0}
#define comm_RawCaptureRequest_init_zero         {0}
#define comm_RawCaptureChunk_init_zero           {0, {{NULL}, NULL}, 0}
#define comm_ResultPoint_init_zero               {0, 0, 0, 0, 0, 0}
#define comm_ResultPointNak_init_zero            {0}
#define comm_ResultPointRetransmit_init_zero     {0, 0, 0, 0, 0}
#define comm_ResultsChunkNak_init_zero           {0}
#define comm_ResultsChunkRetransmit_init_zero    {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0}
#define comm_FwUpdateStartRequest_init_zero      {0, 0, 0, {{NULL}, NULL}}
#define comm_FwUpdateStartResponse_init_zero     {0, {{NULL}, NULL}}
#define comm_FwUpdateChunk_init_zero             {0, {{NULL}, NULL}, 0}
#define comm_FwUpdateChunkAck_init_zero          {0, _comm_FwChunkStatus_MIN}
#define comm_FwUpdateFinishRequest_init_zero     {0}
#define comm_FwUpdateFinishResponse_init_zero    {0, _comm_FwUpdateStatus_MIN, {{NULL}, NULL}}
#define comm_FwUpdateStatusRequest_init_zero     {0}
#define comm_FwUpdateStatusResponse_init_zero    {_comm_FwUpdateStatus_MIN, 0, 0, 0}
#define comm_FwBootConfirmRequest_init_zero      {0}
#define comm_FwBootConfirmResponse_init_zero     {0, {{NULL}, NULL}}
#define comm_Envelope_init_zero                  {0, _comm_MsgType_MIN, 0, {comm_Ping_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define comm_Ping_nonce_tag                      1
#define comm_Pong_nonce_tag                      1
#define comm_SetSettingsRequest_list_length_tag  1
#define comm_SetSettingsRequest_integration_periods_tag 2
#define comm_SetSettingsRequest_use_ema_tag      3
#define comm_SetSettingsResponse_success_tag     1
#define comm_SetListStartRequest_total_floats_tag 1
#define comm_SetListStartResponse_ready_tag      1
#define comm_ListChunk_chunk_index_tag           1
#define comm_ListChunk_values_tag                2
#define comm_ListChunk_is_last_tag               3
#define comm_SetListCompleteResponse_success_tag 1
#define comm_SetListCompleteResponse_floats_received_tag 2
#define comm_StartScanResponse_started_tag       1
#define comm_StartScanResponse_error_tag         2
#define comm_StartScanResponse_transfer_mode_tag 3
#define comm_ResultsChunk_chunk_index_tag        1
#define comm_ResultsChunk_times_tag              2
#define comm_ResultsChunk_x_tag                  3
#define comm_ResultsChunk_y_tag                  4
#define comm_ResultsChunk_is_last_tag            5
#define comm_GetStatusResponse_scan_ongoing_tag  1
#define comm_GetStatusResponse_list_length_tag   2
#define comm_GetStatusResponse_max_list_length_tag 3
#define comm_GetStatusResponse_modulation_frequency_hz_tag 4
#define comm_GetStatusResponse_settings_valid_tag 5
#define comm_GetStatusResponse_list_valid_tag    6
#define comm_GetSerialResponse_serial_tag        1
#define comm_GetVersionResponse_version_tag      1
#define comm_TransformedListChunk_chunk_index_tag 1
#define comm_TransformedListChunk_values_tag     2
#define comm_TransformedListChunk_is_last_tag    3
#define comm_GetCapabilitiesResponse_has_external_dac_tag 1
#define comm_GetCapabilitiesResponse_has_encoder_tag 2
#define comm_GetCapabilitiesResponse_has_i2c1_tag 3
#define comm_GetCapabilitiesResponse_has_i2c2_tag 4
#define comm_GetCapabilitiesResponse_has_i2c3_tag 5
#define comm_GetCapabilitiesResponse_has_power_rails_tag 6
#define comm_RawCaptureRequest_num_samples_tag   1
#define comm_RawCaptureChunk_chunk_index_tag     1
#define comm_RawCaptureChunk_samples_tag         2
#define comm_RawCaptureChunk_is_last_tag         3
#define comm_ResultPoint_point_index_tag         1
#define comm_ResultPoint_time_tag                2
#define comm_ResultPoint_x_tag                   3
#define comm_ResultPoint_y_tag                   4
#define comm_ResultPoint_is_last_tag             5
#define comm_ResultPoint_send_timestamp_us_tag   6
#define comm_ResultPointNak_point_index_tag      1
#define comm_ResultPointRetransmit_point_index_tag 1
#define comm_ResultPointRetransmit_available_tag 2
#define comm_ResultPointRetransmit_time_tag      3
#define comm_ResultPointRetransmit_x_tag         4
#define comm_ResultPointRetransmit_y_tag         5
#define comm_ResultsChunkNak_chunk_index_tag     1
#define comm_ResultsChunkRetransmit_chunk_index_tag 1
#define comm_ResultsChunkRetransmit_times_tag    2
#define comm_ResultsChunkRetransmit_x_tag        3
#define comm_ResultsChunkRetransmit_y_tag        4
#define comm_ResultsChunkRetransmit_is_last_tag  5
#define comm_ResultsChunkRetransmit_available_tag 6
#define comm_FwUpdateStartRequest_firmware_size_tag 1
#define comm_FwUpdateStartRequest_firmware_crc_tag 2
#define comm_FwUpdateStartRequest_chunk_size_tag 3
#define comm_FwUpdateStartRequest_version_tag    4
#define comm_FwUpdateStartResponse_accepted_tag  1
#define comm_FwUpdateStartResponse_error_tag     2
#define comm_FwUpdateChunk_chunk_index_tag       1
#define comm_FwUpdateChunk_data_tag              2
#define comm_FwUpdateChunk_chunk_crc_tag         3
#define comm_FwUpdateChunkAck_chunk_index_tag    1
#define comm_FwUpdateChunkAck_status_tag         2
#define comm_FwUpdateFinishResponse_success_tag  1
#define comm_FwUpdateFinishResponse_status_tag   2
#define comm_FwUpdateFinishResponse_error_tag    3
#define comm_FwUpdateStatusResponse_status_tag   1
#define comm_FwUpdateStatusResponse_chunks_received_tag 2
#define comm_FwUpdateStatusResponse_total_chunks_tag 3
#define comm_FwUpdateStatusResponse_bytes_received_tag 4
#define comm_FwBootConfirmResponse_confirmed_tag 1
#define comm_FwBootConfirmResponse_version_tag   2
#define comm_Envelope_seq_tag                    1
#define comm_Envelope_type_tag                   2
#define comm_Envelope_ping_tag                   10
#define comm_Envelope_pong_tag                   11
#define comm_Envelope_set_settings_request_tag   14
#define comm_Envelope_set_settings_response_tag  15
#define comm_Envelope_set_list_start_request_tag 16
#define comm_Envelope_set_list_start_response_tag 17
#define comm_Envelope_list_chunk_tag             18
#define comm_Envelope_set_list_complete_response_tag 19
#define comm_Envelope_start_scan_request_tag     20
#define comm_Envelope_start_scan_response_tag    21
#define comm_Envelope_get_results_request_tag    22
#define comm_Envelope_results_chunk_tag          23
#define comm_Envelope_get_status_request_tag     24
#define comm_Envelope_get_status_response_tag    25
#define comm_Envelope_get_serial_request_tag     26
#define comm_Envelope_get_serial_response_tag    27
#define comm_Envelope_get_version_request_tag    28
#define comm_Envelope_get_version_response_tag   29
#define comm_Envelope_reboot_request_tag         30
#define comm_Envelope_get_transformed_list_request_tag 31
#define comm_Envelope_transformed_list_chunk_tag 32
#define comm_Envelope_get_capabilities_request_tag 33
#define comm_Envelope_get_capabilities_response_tag 34
#define comm_Envelope_raw_capture_request_tag    35
#define comm_Envelope_raw_capture_chunk_tag      36
#define comm_Envelope_result_point_tag           37
#define comm_Envelope_result_point_nak_tag       38
#define comm_Envelope_result_point_retransmit_tag 39
#define comm_Envelope_fw_update_start_request_tag 40
#define comm_Envelope_fw_update_start_response_tag 41
#define comm_Envelope_fw_update_chunk_tag        42
#define comm_Envelope_fw_update_chunk_ack_tag    43
#define comm_Envelope_fw_update_finish_request_tag 44
#define comm_Envelope_fw_update_finish_response_tag 45
#define comm_Envelope_fw_update_status_request_tag 46
#define comm_Envelope_fw_update_status_response_tag 47
#define comm_Envelope_fw_boot_confirm_request_tag 48
#define comm_Envelope_fw_boot_confirm_response_tag 49
#define comm_Envelope_results_chunk_nak_tag      50
#define comm_Envelope_results_chunk_retransmit_tag 51

/* Struct field encoding specification for nanopb */
#define comm_Ping_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   nonce,             1)
#define comm_Ping_CALLBACK NULL
#define comm_Ping_DEFAULT NULL

#define comm_Pong_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   nonce,             1)
#define comm_Pong_CALLBACK NULL
#define comm_Pong_DEFAULT NULL

#define comm_SetSettingsRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   list_length,       1) \
X(a, STATIC,   SINGULAR, UINT32,   integration_periods,   2) \
X(a, STATIC,   SINGULAR, BOOL,     use_ema,           3)
#define comm_SetSettingsRequest_CALLBACK NULL
#define comm_SetSettingsRequest_DEFAULT NULL

#define comm_SetSettingsResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1)
#define comm_SetSettingsResponse_CALLBACK NULL
#define comm_SetSettingsResponse_DEFAULT NULL

#define comm_SetListStartRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   total_floats,      1)
#define comm_SetListStartRequest_CALLBACK NULL
#define comm_SetListStartRequest_DEFAULT NULL

#define comm_SetListStartResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     ready,             1)
#define comm_SetListStartResponse_CALLBACK NULL
#define comm_SetListStartResponse_DEFAULT NULL

#define comm_ListChunk_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   chunk_index,       1) \
X(a, CALLBACK, REPEATED, FLOAT,    values,            2) \
X(a, STATIC,   SINGULAR, BOOL,     is_last,           3)
#define comm_ListChunk_CALLBACK pb_default_field_callback
#define comm_ListChunk_DEFAULT NULL

#define comm_SetListCompleteResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, STATIC,   SINGULAR, UINT32,   floats_received,   2)
#define comm_SetListCompleteResponse_CALLBACK NULL
#define comm_SetListCompleteResponse_DEFAULT NULL

#define comm_StartScanRequest_FIELDLIST(X, a) \

#define comm_StartScanRequest_CALLBACK NULL
#define comm_StartScanRequest_DEFAULT NULL

#define comm_StartScanResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     started,           1) \
X(a, CALLBACK, SINGULAR, STRING,   error,             2) \
X(a, STATIC,   SINGULAR, UENUM,    transfer_mode,     3)
#define comm_StartScanResponse_CALLBACK pb_default_field_callback
#define comm_StartScanResponse_DEFAULT NULL

#define comm_GetResultsRequest_FIELDLIST(X, a) \

#define comm_GetResultsRequest_CALLBACK NULL
#define comm_GetResultsRequest_DEFAULT NULL

#define comm_ResultsChunk_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   chunk_index,       1) \
X(a, CALLBACK, REPEATED, FLOAT,    times,             2) \
X(a, CALLBACK, REPEATED, FLOAT,    x,                 3) \
X(a, CALLBACK, REPEATED, FLOAT,    y,                 4) \
X(a, STATIC,   SINGULAR, BOOL,     is_last,           5)
#define comm_ResultsChunk_CALLBACK pb_default_field_callback
#define comm_ResultsChunk_DEFAULT NULL

#define comm_GetStatusRequest_FIELDLIST(X, a) \

#define comm_GetStatusRequest_CALLBACK NULL
#define comm_GetStatusRequest_DEFAULT NULL

#define comm_GetStatusResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     scan_ongoing,      1) \
X(a, STATIC,   SINGULAR, UINT32,   list_length,       2) \
X(a, STATIC,   SINGULAR, UINT32,   max_list_length,   3) \
X(a, STATIC,   SINGULAR, UINT32,   modulation_frequency_hz,   4) \
X(a, STATIC,   SINGULAR, BOOL,     settings_valid,    5) \
X(a, STATIC,   SINGULAR, BOOL,     list_valid,        6)
#define comm_GetStatusResponse_CALLBACK NULL
#define comm_GetStatusResponse_DEFAULT NULL

#define comm_GetSerialRequest_FIELDLIST(X, a) \

#define comm_GetSerialRequest_CALLBACK NULL
#define comm_GetSerialRequest_DEFAULT NULL

#define comm_GetSerialResponse_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   serial,            1)
#define comm_GetSerialResponse_CALLBACK pb_default_field_callback
#define comm_GetSerialResponse_DEFAULT NULL

#define comm_GetVersionRequest_FIELDLIST(X, a) \

#define comm_GetVersionRequest_CALLBACK NULL
#define comm_GetVersionRequest_DEFAULT NULL

#define comm_GetVersionResponse_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   version,           1)
#define comm_GetVersionResponse_CALLBACK pb_default_field_callback
#define comm_GetVersionResponse_DEFAULT NULL

#define comm_RebootRequest_FIELDLIST(X, a) \

#define comm_RebootRequest_CALLBACK NULL
#define comm_RebootRequest_DEFAULT NULL

#define comm_GetTransformedListRequest_FIELDLIST(X, a) \

#define comm_GetTransformedListRequest_CALLBACK NULL
#define comm_GetTransformedListRequest_DEFAULT NULL

#define comm_TransformedListChunk_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   chunk_index,       1) \
X(a, CALLBACK, REPEATED, UINT32,   values,            2) \
X(a, STATIC,   SINGULAR, BOOL,     is_last,           3)
#define comm_TransformedListChunk_CALLBACK pb_default_field_callback
#define comm_TransformedListChunk_DEFAULT NULL

#define comm_GetCapabilitiesRequest_FIELDLIST(X, a) \

#define comm_GetCapabilitiesRequest_CALLBACK NULL
#define comm_GetCapabilitiesRequest_DEFAULT NULL

#define comm_GetCapabilitiesResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     has_external_dac,   1) \
X(a, STATIC,   SINGULAR, BOOL,     has_encoder,       2) \
X(a, STATIC,   SINGULAR, BOOL,     has_i2c1,          3) \
X(a, STATIC,   SINGULAR, BOOL,     has_i2c2,          4) \
X(a, STATIC,   SINGULAR, BOOL,     has_i2c3,          5) \
X(a, STATIC,   SINGULAR, BOOL,     has_power_rails,   6)
#define comm_GetCapabilitiesResponse_CALLBACK NULL
#define comm_GetCapabilitiesResponse_DEFAULT NULL

#define comm_RawCaptureRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   num_samples,       1)
#define comm_RawCaptureRequest_CALLBACK NULL
#define comm_RawCaptureRequest_DEFAULT NULL

#define comm_RawCaptureChunk_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   chunk_index,       1) \
X(a, CALLBACK, REPEATED, UINT32,   samples,           2) \
X(a, STATIC,   SINGULAR, BOOL,     is_last,           3)
#define comm_RawCaptureChunk_CALLBACK pb_default_field_callback
#define comm_RawCaptureChunk_DEFAULT NULL

#define comm_ResultPoint_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   point_index,       1) \
X(a, STATIC,   SINGULAR, FLOAT,    time,              2) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 3) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 4) \
X(a, STATIC,   SINGULAR, BOOL,     is_last,           5) \
X(a, STATIC,   SINGULAR, UINT32,   send_timestamp_us,   6)
#define comm_ResultPoint_CALLBACK NULL
#define comm_ResultPoint_DEFAULT NULL

#define comm_ResultPointNak_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   point_index,       1)
#define comm_ResultPointNak_CALLBACK NULL
#define comm_ResultPointNak_DEFAULT NULL

#define comm_ResultPointRetransmit_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   point_index,       1) \
X(a, STATIC,   SINGULAR, BOOL,     available,         2) \
X(a, STATIC,   SINGULAR, FLOAT,    time,              3) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 4) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 5)
#define comm_ResultPointRetransmit_CALLBACK NULL
#define comm_ResultPointRetransmit_DEFAULT NULL

#define comm_ResultsChunkNak_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   chunk_index,       1)
#define comm_ResultsChunkNak_CALLBACK NULL
#define comm_ResultsChunkNak_DEFAULT NULL

#define comm_ResultsChunkRetransmit_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   chunk_index,       1) \
X(a, CALLBACK, REPEATED, FLOAT,    times,             2) \
X(a, CALLBACK, REPEATED, FLOAT,    x,                 3) \
X(a, CALLBACK, REPEATED, FLOAT,    y,                 4) \
X(a, STATIC,   SINGULAR, BOOL,     is_last,           5) \
X(a, STATIC,   SINGULAR, BOOL,     available,         6)
#define comm_ResultsChunkRetransmit_CALLBACK pb_default_field_callback
#define comm_ResultsChunkRetransmit_DEFAULT NULL

#define comm_FwUpdateStartRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   firmware_size,     1) \
X(a, STATIC,   SINGULAR, UINT32,   firmware_crc,      2) \
X(a, STATIC,   SINGULAR, UINT32,   chunk_size,        3) \
X(a, CALLBACK, SINGULAR, STRING,   version,           4)
#define comm_FwUpdateStartRequest_CALLBACK pb_default_field_callback
#define comm_FwUpdateStartRequest_DEFAULT NULL

#define comm_FwUpdateStartResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     accepted,          1) \
X(a, CALLBACK, SINGULAR, STRING,   error,             2)
#define comm_FwUpdateStartResponse_CALLBACK pb_default_field_callback
#define comm_FwUpdateStartResponse_DEFAULT NULL

#define comm_FwUpdateChunk_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   chunk_index,       1) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              2) \
X(a, STATIC,   SINGULAR, UINT32,   chunk_crc,         3)
#define comm_FwUpdateChunk_CALLBACK pb_default_field_callback
#define comm_FwUpdateChunk_DEFAULT NULL

#define comm_FwUpdateChunkAck_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   chunk_index,       1) \
X(a, STATIC,   SINGULAR, UENUM,    status,            2)
#define comm_FwUpdateChunkAck_CALLBACK NULL
#define comm_FwUpdateChunkAck_DEFAULT NULL

#define comm_FwUpdateFinishRequest_FIELDLIST(X, a) \

#define comm_FwUpdateFinishRequest_CALLBACK NULL
#define comm_FwUpdateFinishRequest_DEFAULT NULL

#define comm_FwUpdateFinishResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, STATIC,   SINGULAR, UENUM,    status,            2) \
X(a, CALLBACK, SINGULAR, STRING,   error,             3)
#define comm_FwUpdateFinishResponse_CALLBACK pb_default_field_callback
#define comm_FwUpdateFinishResponse_DEFAULT NULL

#define comm_FwUpdateStatusRequest_FIELDLIST(X, a) \

#define comm_FwUpdateStatusRequest_CALLBACK NULL
#define comm_FwUpdateStatusRequest_DEFAULT NULL

#define comm_FwUpdateStatusResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    status,            1) \
X(a, STATIC,   SINGULAR, UINT32,   chunks_received,   2) \
X(a, STATIC,   SINGULAR, UINT32,   total_chunks,      3) \
X(a, STATIC,   SINGULAR, UINT32,   bytes_received,    4)
#define comm_FwUpdateStatusResponse_CALLBACK NULL
#define comm_FwUpdateStatusResponse_DEFAULT NULL

#define comm_FwBootConfirmRequest_FIELDLIST(X, a) \

#define comm_FwBootConfirmRequest_CALLBACK NULL
#define comm_FwBootConfirmRequest_DEFAULT NULL

#define comm_FwBootConfirmResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     confirmed,         1) \
X(a, CALLBACK, SINGULAR, STRING,   version,           2)
#define comm_FwBootConfirmResponse_CALLBACK pb_default_field_callback
#define comm_FwBootConfirmResponse_DEFAULT NULL

#define comm_Envelope_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   seq,               1) \
X(a, STATIC,   SINGULAR, UENUM,    type,              2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ping,payload.ping),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,pong,payload.pong),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_settings_request,payload.set_settings_request),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_settings_response,payload.set_settings_response),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_list_start_request,payload.set_list_start_request),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_list_start_response,payload.set_list_start_response),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,list_chunk,payload.list_chunk),  18) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_list_complete_response,payload.set_list_complete_response),  19) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,start_scan_request,payload.start_scan_request),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,start_scan_response,payload.start_scan_response),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,get_results_request,payload.get_results_request),  22) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,results_chunk,payload.results_chunk),  23) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,get_status_request,payload.get_status_request),  24) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,get_status_response,payload.get_status_response),  25) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,get_serial_request,payload.get_serial_request),  26) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,get_serial_response,payload.get_serial_response),  27) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,get_version_request,payload.get_version_request),  28) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,get_version_response,payload.get_version_response),  29) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,reboot_request,payload.reboot_request),  30) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,get_transformed_list_request,payload.get_transformed_list_request),  31) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,transformed_list_chunk,payload.transformed_list_chunk),  32) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,get_capabilities_request,payload.get_capabilities_request),  33) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,get_capabilities_response,payload.get_capabilities_response),  34) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,raw_capture_request,payload.raw_capture_request),  35) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,raw_capture_chunk,payload.raw_capture_chunk),  36) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,result_point,payload.result_point),  37) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,result_point_nak,payload.result_point_nak),  38) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,result_point_retransmit,payload.result_point_retransmit),  39) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,fw_update_start_request,payload.fw_update_start_request),  40) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,fw_update_start_response,payload.fw_update_start_response),  41) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,fw_update_chunk,payload.fw_update_chunk),  42) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,fw_update_chunk_ack,payload.fw_update_chunk_ack),  43) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,fw_update_finish_request,payload.fw_update_finish_request),  44) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,fw_update_finish_response,payload.fw_update_finish_response),  45) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,fw_update_status_request,payload.fw_update_status_request),  46) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,fw_update_status_response,payload.fw_update_status_response),  47) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,fw_boot_confirm_request,payload.fw_boot_confirm_request),  48) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,fw_boot_confirm_response,payload.fw_boot_confirm_response),  49) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,results_chunk_nak,payload.results_chunk_nak),  50) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,results_chunk_retransmit,payload.results_chunk_retransmit),  51)
#define comm_Envelope_CALLBACK NULL
#define comm_Envelope_DEFAULT NULL
#define comm_Envelope_payload_ping_MSGTYPE comm_Ping
#define comm_Envelope_payload_pong_MSGTYPE comm_Pong
#define comm_Envelope_payload_set_settings_request_MSGTYPE comm_SetSettingsRequest
#define comm_Envelope_payload_set_settings_response_MSGTYPE comm_SetSettingsResponse
#define comm_Envelope_payload_set_list_start_request_MSGTYPE comm_SetListStartRequest
#define comm_Envelope_payload_set_list_start_response_MSGTYPE comm_SetListStartResponse
#define comm_Envelope_payload_list_chunk_MSGTYPE comm_ListChunk
#define comm_Envelope_payload_set_list_complete_response_MSGTYPE comm_SetListCompleteResponse
#define comm_Envelope_payload_start_scan_request_MSGTYPE comm_StartScanRequest
#define comm_Envelope_payload_start_scan_response_MSGTYPE comm_StartScanResponse
#define comm_Envelope_payload_get_results_request_MSGTYPE comm_GetResultsRequest
#define comm_Envelope_payload_results_chunk_MSGTYPE comm_ResultsChunk
#define comm_Envelope_payload_get_status_request_MSGTYPE comm_GetStatusRequest
#define comm_Envelope_payload_get_status_response_MSGTYPE comm_GetStatusResponse
#define comm_Envelope_payload_get_serial_request_MSGTYPE comm_GetSerialRequest
#define comm_Envelope_payload_get_serial_response_MSGTYPE comm_GetSerialResponse
#define comm_Envelope_payload_get_version_request_MSGTYPE comm_GetVersionRequest
#define comm_Envelope_payload_get_version_response_MSGTYPE comm_GetVersionResponse
#define comm_Envelope_payload_reboot_request_MSGTYPE comm_RebootRequest
#define comm_Envelope_payload_get_transformed_list_request_MSGTYPE comm_GetTransformedListRequest
#define comm_Envelope_payload_transformed_list_chunk_MSGTYPE comm_TransformedListChunk
#define comm_Envelope_payload_get_capabilities_request_MSGTYPE comm_GetCapabilitiesRequest
#define comm_Envelope_payload_get_capabilities_response_MSGTYPE comm_GetCapabilitiesResponse
#define comm_Envelope_payload_raw_capture_request_MSGTYPE comm_RawCaptureRequest
#define comm_Envelope_payload_raw_capture_chunk_MSGTYPE comm_RawCaptureChunk
#define comm_Envelope_payload_result_point_MSGTYPE comm_ResultPoint
#define comm_Envelope_payload_result_point_nak_MSGTYPE comm_ResultPointNak
#define comm_Envelope_payload_result_point_retransmit_MSGTYPE comm_ResultPointRetransmit
#define comm_Envelope_payload_fw_update_start_request_MSGTYPE comm_FwUpdateStartRequest
#define comm_Envelope_payload_fw_update_start_response_MSGTYPE comm_FwUpdateStartResponse
#define comm_Envelope_payload_fw_update_chunk_MSGTYPE comm_FwUpdateChunk
#define comm_Envelope_payload_fw_update_chunk_ack_MSGTYPE comm_FwUpdateChunkAck
#define comm_Envelope_payload_fw_update_finish_request_MSGTYPE comm_FwUpdateFinishRequest
#define comm_Envelope_payload_fw_update_finish_response_MSGTYPE comm_FwUpdateFinishResponse
#define comm_Envelope_payload_fw_update_status_request_MSGTYPE comm_FwUpdateStatusRequest
#define comm_Envelope_payload_fw_update_status_response_MSGTYPE comm_FwUpdateStatusResponse
#define comm_Envelope_payload_fw_boot_confirm_request_MSGTYPE comm_FwBootConfirmRequest
#define comm_Envelope_payload_fw_boot_confirm_response_MSGTYPE comm_FwBootConfirmResponse
#define comm_Envelope_payload_results_chunk_nak_MSGTYPE comm_ResultsChunkNak
#define comm_Envelope_payload_results_chunk_retransmit_MSGTYPE comm_ResultsChunkRetransmit

extern const pb_msgdesc_t comm_Ping_msg;
extern const pb_msgdesc_t comm_Pong_msg;
extern const pb_msgdesc_t comm_SetSettingsRequest_msg;
extern const pb_msgdesc_t comm_SetSettingsResponse_msg;
extern const pb_msgdesc_t comm_SetListStartRequest_msg;
extern const pb_msgdesc_t comm_SetListStartResponse_msg;
extern const pb_msgdesc_t comm_ListChunk_msg;
extern const pb_msgdesc_t comm_SetListCompleteResponse_msg;
extern const pb_msgdesc_t comm_StartScanRequest_msg;
extern const pb_msgdesc_t comm_StartScanResponse_msg;
extern const pb_msgdesc_t comm_GetResultsRequest_msg;
extern const pb_msgdesc_t comm_ResultsChunk_msg;
extern const pb_msgdesc_t comm_GetStatusRequest_msg;
extern const pb_msgdesc_t comm_GetStatusResponse_msg;
extern const pb_msgdesc_t comm_GetSerialRequest_msg;
extern const pb_msgdesc_t comm_GetSerialResponse_msg;
extern const pb_msgdesc_t comm_GetVersionRequest_msg;
extern const pb_msgdesc_t comm_GetVersionResponse_msg;
extern const pb_msgdesc_t comm_RebootRequest_msg;
extern const pb_msgdesc_t comm_GetTransformedListRequest_msg;
extern const pb_msgdesc_t comm_TransformedListChunk_msg;
extern const pb_msgdesc_t comm_GetCapabilitiesRequest_msg;
extern const pb_msgdesc_t comm_GetCapabilitiesResponse_msg;
extern const pb_msgdesc_t comm_RawCaptureRequest_msg;
extern const pb_msgdesc_t comm_RawCaptureChunk_msg;
extern const pb_msgdesc_t comm_ResultPoint_msg;
extern const pb_msgdesc_t comm_ResultPointNak_msg;
extern const pb_msgdesc_t comm_ResultPointRetransmit_msg;
extern const pb_msgdesc_t comm_ResultsChunkNak_msg;
extern const pb_msgdesc_t comm_ResultsChunkRetransmit_msg;
extern const pb_msgdesc_t comm_FwUpdateStartRequest_msg;
extern const pb_msgdesc_t comm_FwUpdateStartResponse_msg;
extern const pb_msgdesc_t comm_FwUpdateChunk_msg;
extern const pb_msgdesc_t comm_FwUpdateChunkAck_msg;
extern const pb_msgdesc_t comm_FwUpdateFinishRequest_msg;
extern const pb_msgdesc_t comm_FwUpdateFinishResponse_msg;
extern const pb_msgdesc_t comm_FwUpdateStatusRequest_msg;
extern const pb_msgdesc_t comm_FwUpdateStatusResponse_msg;
extern const pb_msgdesc_t comm_FwBootConfirmRequest_msg;
extern const pb_msgdesc_t comm_FwBootConfirmResponse_msg;
extern const pb_msgdesc_t comm_Envelope_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define comm_Ping_fields &comm_Ping_msg
#define comm_Pong_fields &comm_Pong_msg
#define comm_SetSettingsRequest_fields &comm_SetSettingsRequest_msg
#define comm_SetSettingsResponse_fields &comm_SetSettingsResponse_msg
#define comm_SetListStartRequest_fields &comm_SetListStartRequest_msg
#define comm_SetListStartResponse_fields &comm_SetListStartResponse_msg
#define comm_ListChunk_fields &comm_ListChunk_msg
#define comm_SetListCompleteResponse_fields &comm_SetListCompleteResponse_msg
#define comm_StartScanRequest_fields &comm_StartScanRequest_msg
#define comm_StartScanResponse_fields &comm_StartScanResponse_msg
#define comm_GetResultsRequest_fields &comm_GetResultsRequest_msg
#define comm_ResultsChunk_fields &comm_ResultsChunk_msg
#define comm_GetStatusRequest_fields &comm_GetStatusRequest_msg
#define comm_GetStatusResponse_fields &comm_GetStatusResponse_msg
#define comm_GetSerialRequest_fields &comm_GetSerialRequest_msg
#define comm_GetSerialResponse_fields &comm_GetSerialResponse_msg
#define comm_GetVersionRequest_fields &comm_GetVersionRequest_msg
#define comm_GetVersionResponse_fields &comm_GetVersionResponse_msg
#define comm_RebootRequest_fields &comm_RebootRequest_msg
#define comm_GetTransformedListRequest_fields &comm_GetTransformedListRequest_msg
#define comm_TransformedListChunk_fields &comm_TransformedListChunk_msg
#define comm_GetCapabilitiesRequest_fields &comm_GetCapabilitiesRequest_msg
#define comm_GetCapabilitiesResponse_fields &comm_GetCapabilitiesResponse_msg
#define comm_RawCaptureRequest_fields &comm_RawCaptureRequest_msg
#define comm_RawCaptureChunk_fields &comm_RawCaptureChunk_msg
#define comm_ResultPoint_fields &comm_ResultPoint_msg
#define comm_ResultPointNak_fields &comm_ResultPointNak_msg
#define comm_ResultPointRetransmit_fields &comm_ResultPointRetransmit_msg
#define comm_ResultsChunkNak_fields &comm_ResultsChunkNak_msg
#define comm_ResultsChunkRetransmit_fields &comm_ResultsChunkRetransmit_msg
#define comm_FwUpdateStartRequest_fields &comm_FwUpdateStartRequest_msg
#define comm_FwUpdateStartResponse_fields &comm_FwUpdateStartResponse_msg
#define comm_FwUpdateChunk_fields &comm_FwUpdateChunk_msg
#define comm_FwUpdateChunkAck_fields &comm_FwUpdateChunkAck_msg
#define comm_FwUpdateFinishRequest_fields &comm_FwUpdateFinishRequest_msg
#define comm_FwUpdateFinishResponse_fields &comm_FwUpdateFinishResponse_msg
#define comm_FwUpdateStatusRequest_fields &comm_FwUpdateStatusRequest_msg
#define comm_FwUpdateStatusResponse_fields &comm_FwUpdateStatusResponse_msg
#define comm_FwBootConfirmRequest_fields &comm_FwBootConfirmRequest_msg
#define comm_FwBootConfirmResponse_fields &comm_FwBootConfirmResponse_msg
#define comm_Envelope_fields &comm_Envelope_msg

/* Maximum encoded size of messages (where known) */
/* comm_ListChunk_size depends on runtime parameters */
/* comm_StartScanResponse_size depends on runtime parameters */
/* comm_ResultsChunk_size depends on runtime parameters */
/* comm_GetSerialResponse_size depends on runtime parameters */
/* comm_GetVersionResponse_size depends on runtime parameters */
/* comm_TransformedListChunk_size depends on runtime parameters */
/* comm_RawCaptureChunk_size depends on runtime parameters */
/* comm_ResultsChunkRetransmit_size depends on runtime parameters */
/* comm_FwUpdateStartRequest_size depends on runtime parameters */
/* comm_FwUpdateStartResponse_size depends on runtime parameters */
/* comm_FwUpdateChunk_size depends on runtime parameters */
/* comm_FwUpdateFinishResponse_size depends on runtime parameters */
/* comm_FwBootConfirmResponse_size depends on runtime parameters */
/* comm_Envelope_size depends on runtime parameters */
#define COMM_ENVELOPE_PB_H_MAX_SIZE              comm_ResultPoint_size
#define comm_FwBootConfirmRequest_size           0
#define comm_FwUpdateChunkAck_size               8
#define comm_FwUpdateFinishRequest_size          0
#define comm_FwUpdateStatusRequest_size          0
#define comm_FwUpdateStatusResponse_size         20
#define comm_GetCapabilitiesRequest_size         0
#define comm_GetCapabilitiesResponse_size        12
#define comm_GetResultsRequest_size              0
#define comm_GetSerialRequest_size               0
#define comm_GetStatusRequest_size               0
#define comm_GetStatusResponse_size              24
#define comm_GetTransformedListRequest_size      0
#define comm_GetVersionRequest_size              0
#define comm_Ping_size                           6
#define comm_Pong_size                           6
#define comm_RawCaptureRequest_size              6
#define comm_RebootRequest_size                  0
#define comm_ResultPointNak_size                 6
#define comm_ResultPointRetransmit_size          23
#define comm_ResultPoint_size                    29
#define comm_ResultsChunkNak_size                6
#define comm_SetListCompleteResponse_size        8
#define comm_SetListStartRequest_size            6
#define comm_SetListStartResponse_size           2
#define comm_SetSettingsRequest_size             14
#define comm_SetSettingsResponse_size            2
#define comm_StartScanRequest_size               0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
