/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "envelope.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(comm_Ping, comm_Ping, AUTO)


PB_BIND(comm_Pong, comm_Pong, AUTO)


PB_BIND(comm_SetSettingsRequest, comm_SetSettingsRequest, AUTO)


PB_BIND(comm_SetSettingsResponse, comm_SetSettingsResponse, AUTO)


PB_BIND(comm_SetListStartRequest, comm_SetListStartRequest, AUTO)


PB_BIND(comm_SetListStartResponse, comm_SetListStartResponse, AUTO)


PB_BIND(comm_ListChunk, comm_ListChunk, AUTO)


PB_BIND(comm_SetListCompleteResponse, comm_SetListCompleteResponse, AUTO)


PB_BIND(comm_StartScanRequest, comm_StartScanRequest, AUTO)


PB_BIND(comm_StartScanResponse, comm_StartScanResponse, AUTO)


PB_BIND(comm_GetResultsRequest, comm_GetResultsRequest, AUTO)


PB_BIND(comm_ResultsChunk, comm_ResultsChunk, AUTO)


PB_BIND(comm_GetStatusRequest, comm_GetStatusRequest, AUTO)


PB_BIND(comm_GetStatusResponse, comm_GetStatusResponse, AUTO)


PB_BIND(comm_GetSerialRequest, comm_GetSerialRequest, AUTO)


PB_BIND(comm_GetSerialResponse, comm_GetSerialResponse, AUTO)


PB_BIND(comm_GetVersionRequest, comm_GetVersionRequest, AUTO)


PB_BIND(comm_GetVersionResponse, comm_GetVersionResponse, AUTO)


PB_BIND(comm_RebootRequest, comm_RebootRequest, AUTO)


PB_BIND(comm_GetTransformedListRequest, comm_GetTransformedListRequest, AUTO)


PB_BIND(comm_TransformedListChunk, comm_TransformedListChunk, AUTO)


PB_BIND(comm_GetCapabilitiesRequest, comm_GetCapabilitiesRequest, AUTO)


PB_BIND(comm_GetCapabilitiesResponse, comm_GetCapabilitiesResponse, AUTO)


PB_BIND(comm_RawCaptureRequest, comm_RawCaptureRequest, AUTO)


PB_BIND(comm_RawCaptureChunk, comm_RawCaptureChunk, AUTO)


PB_BIND(comm_ResultPoint, comm_ResultPoint, AUTO)


PB_BIND(comm_ResultPointNak, comm_ResultPointNak, AUTO)


PB_BIND(comm_ResultPointRetransmit, comm_ResultPointRetransmit, AUTO)


PB_BIND(comm_ResultsChunkNak, comm_ResultsChunkNak, AUTO)


PB_BIND(comm_ResultsChunkRetransmit, comm_ResultsChunkRetransmit, AUTO)


PB_BIND(comm_FwUpdateStartRequest, comm_FwUpdateStartRequest, AUTO)


PB_BIND(comm_FwUpdateStartResponse, comm_FwUpdateStartResponse, AUTO)


PB_BIND(comm_FwUpdateChunk, comm_FwUpdateChunk, AUTO)


PB_BIND(comm_FwUpdateChunkAck, comm_FwUpdateChunkAck, AUTO)


PB_BIND(comm_FwUpdateFinishRequest, comm_FwUpdateFinishRequest, AUTO)


PB_BIND(comm_FwUpdateFinishResponse, comm_FwUpdateFinishResponse, AUTO)


PB_BIND(comm_FwUpdateStatusRequest, comm_FwUpdateStatusRequest, AUTO)


PB_BIND(comm_FwUpdateStatusResponse, comm_FwUpdateStatusResponse, AUTO)


PB_BIND(comm_FwBootConfirmRequest, comm_FwBootConfirmRequest, AUTO)


PB_BIND(comm_FwBootConfirmResponse, comm_FwBootConfirmResponse, AUTO)


PB_BIND(comm_Envelope, comm_Envelope, AUTO)











