# Releases new version. A release merely entails tagging the main branch with a correct semantic version
# This approach is taken, since GitHub doesn't support private package repositories for Python.
name: Release
run-name: Release
# on: workflow_dispatch
on: 
  push:
    branches:
      - "bmo/migrate"
jobs:
  tag-release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          pip install -r requirements-build.txt
          pip install -r requirements-docs.txt
      - name: Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Build package
        run: python -m build
      - name: Publish package
        env:
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
        run: twine upload -r testpypi dist/*
      - name: Publish documentation
        run: |
          mike deploy --push --update-aliases $(bumpver show --environ | grep "CURRENT_VERSION" | cut -d'=' -f2 | tr -d ' ') latest
