# Releases new version. A release merely entails tagging the main branch with a correct semantic version
# This approach is taken, since GitHub doesn't support private package repositories for Python.
name: Release
run-name: Release
on: workflow_dispatch

jobs:
  tag-release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: pip install -r requirements-build.txt
      - name: Build package
        run: python -m build
      - name: Publish package
        run: twine upload dist/*
      - name: Create tag
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner, 
              repo: context.repo.repo, 
              ref: "refs/tags/v$(bumpver show --environ | grep "CURRENT_VERSION" | cut -d'=' -f2 | tr -d ' ')", 
              sha: context.sha
            })
      - name: Publish documentation
        uses: actions/github-script@v6
        with:
          script: |
            pip install -r requirements-docs.txt
            mike deploy --push --update-aliases $(bumpver show --environ | grep "CURRENT_VERSION" | cut -d'=' -f2 | tr -d ' ') latest
